// Код сгенерирован генератором грамматики; руками не править.
package action

import (
	"github.com/fugalang/fugu/internal/ast"
	. "github.com/fugalang/fugu/internal/token"
)

var ActionMap = &map[int]map[Kind]ActionStruct{
	0: {
		USE: Sh(24),
		LET: Sh(15),
		IF: Sh(10),
		RETURN: Sh(20),
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		R_BRACE: Red(0, ast.Items),
		ADD: Sh(1),
		SUB: Sh(23),
		EOF: Red(0, ast.Items),
	},
	1: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	2: {
		R_PAREN: Red(1, ast.Expr),
		L_BRACE: Red(1, ast.Expr),
		COMMA: Red(1, ast.Expr),
		END: Red(1, ast.Expr),
	},
	3: {
		R_PAREN: Red(1, ast.AssignExpr),
		L_BRACE: Red(1, ast.AssignExpr),
		ADD: Sh(29),
		SUB: Sh(39),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Sh(31),
		NEQ: Sh(38),
		LT: Sh(35),
		GT: Sh(33),
		LE: Sh(34),
		GE: Sh(32),
		COMMA: Red(1, ast.AssignExpr),
		END: Red(1, ast.AssignExpr),
	},
	4: {
		R_PAREN: Red(1, ast.Literal),
		L_BRACE: Red(1, ast.Literal),
		ADD: Red(1, ast.Literal),
		SUB: Red(1, ast.Literal),
		MUL: Red(1, ast.Literal),
		DIV: Red(1, ast.Literal),
		MOD: Red(1, ast.Literal),
		EQ: Red(1, ast.Literal),
		NEQ: Red(1, ast.Literal),
		LT: Red(1, ast.Literal),
		GT: Red(1, ast.Literal),
		LE: Red(1, ast.Literal),
		GE: Red(1, ast.Literal),
		COMMA: Red(1, ast.Literal),
		END: Red(1, ast.Literal),
	},
	5: {
		R_PAREN: Red(1, ast.Primary),
		L_BRACE: Red(1, ast.Primary),
		ADD: Red(1, ast.Primary),
		SUB: Red(1, ast.Primary),
		MUL: Red(1, ast.Primary),
		DIV: Red(1, ast.Primary),
		MOD: Red(1, ast.Primary),
		EQ: Red(1, ast.Primary),
		NEQ: Red(1, ast.Primary),
		LT: Red(1, ast.Primary),
		GT: Red(1, ast.Primary),
		LE: Red(1, ast.Primary),
		GE: Red(1, ast.Primary),
		COMMA: Red(1, ast.Primary),
		END: Red(1, ast.Primary),
	},
	6: {
		END: Sh(40),
	},
	7: {
		USE: Red(1, ast.Item),
		LET: Red(1, ast.Item),
		IF: Red(1, ast.Item),
		RETURN: Red(1, ast.Item),
		IDENTIFIER: Red(1, ast.Item),
		INTEGER: Red(1, ast.Item),
		FLOATING: Red(1, ast.Item),
		STRING: Red(1, ast.Item),
		CHARACTER: Red(1, ast.Item),
		L_PAREN: Red(1, ast.Item),
		R_BRACE: Red(1, ast.Item),
		ADD: Red(1, ast.Item),
		SUB: Red(1, ast.Item),
		EOF: Red(1, ast.Item),
	},
	8: {
		R_PAREN: Red(1, ast.Literal),
		L_BRACE: Red(1, ast.Literal),
		ADD: Red(1, ast.Literal),
		SUB: Red(1, ast.Literal),
		MUL: Red(1, ast.Literal),
		DIV: Red(1, ast.Literal),
		MOD: Red(1, ast.Literal),
		EQ: Red(1, ast.Literal),
		NEQ: Red(1, ast.Literal),
		LT: Red(1, ast.Literal),
		GT: Red(1, ast.Literal),
		LE: Red(1, ast.Literal),
		GE: Red(1, ast.Literal),
		COMMA: Red(1, ast.Literal),
		END: Red(1, ast.Literal),
	},
	9: {
		L_PAREN: Sh(42),
		R_PAREN: Red(1, ast.Ident),
		L_BRACE: Red(1, ast.Ident),
		ASSIGN: Sh(41),
		ADD: Red(1, ast.Ident),
		SUB: Red(1, ast.Ident),
		MUL: Red(1, ast.Ident),
		DIV: Red(1, ast.Ident),
		MOD: Red(1, ast.Ident),
		EQ: Red(1, ast.Ident),
		NEQ: Red(1, ast.Ident),
		LT: Red(1, ast.Ident),
		GT: Red(1, ast.Ident),
		LE: Red(1, ast.Ident),
		GE: Red(1, ast.Ident),
		COMMA: Red(1, ast.Ident),
		END: Red(1, ast.Ident),
	},
	10: {
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	11: {
		R_PAREN: Red(1, ast.Literal),
		L_BRACE: Red(1, ast.Literal),
		ADD: Red(1, ast.Literal),
		SUB: Red(1, ast.Literal),
		MUL: Red(1, ast.Literal),
		DIV: Red(1, ast.Literal),
		MOD: Red(1, ast.Literal),
		EQ: Red(1, ast.Literal),
		NEQ: Red(1, ast.Literal),
		LT: Red(1, ast.Literal),
		GT: Red(1, ast.Literal),
		LE: Red(1, ast.Literal),
		GE: Red(1, ast.Literal),
		COMMA: Red(1, ast.Literal),
		END: Red(1, ast.Literal),
	},
	12: {
		USE: Red(1, ast.Item),
		LET: Red(1, ast.Item),
		IF: Red(1, ast.Item),
		RETURN: Red(1, ast.Item),
		IDENTIFIER: Red(1, ast.Item),
		INTEGER: Red(1, ast.Item),
		FLOATING: Red(1, ast.Item),
		STRING: Red(1, ast.Item),
		CHARACTER: Red(1, ast.Item),
		L_PAREN: Red(1, ast.Item),
		R_BRACE: Red(1, ast.Item),
		ADD: Red(1, ast.Item),
		SUB: Red(1, ast.Item),
		EOF: Red(1, ast.Item),
	},
	13: {
		USE: Sh(24),
		LET: Sh(15),
		IF: Sh(10),
		RETURN: Sh(20),
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		R_BRACE: Red(0, ast.Items),
		ADD: Sh(1),
		SUB: Sh(23),
		EOF: Red(0, ast.Items),
	},
	14: {
		EOF: Sh(45),
	},
	15: {
		IDENTIFIER: Sh(46),
	},
	16: {
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	17: {
		USE: Red(1, ast.Item),
		LET: Red(1, ast.Item),
		IF: Red(1, ast.Item),
		RETURN: Red(1, ast.Item),
		IDENTIFIER: Red(1, ast.Item),
		INTEGER: Red(1, ast.Item),
		FLOATING: Red(1, ast.Item),
		STRING: Red(1, ast.Item),
		CHARACTER: Red(1, ast.Item),
		L_PAREN: Red(1, ast.Item),
		R_BRACE: Red(1, ast.Item),
		ADD: Red(1, ast.Item),
		SUB: Red(1, ast.Item),
		EOF: Red(1, ast.Item),
	},
	18: {
		R_PAREN: Red(1, ast.UnaryExpr),
		L_BRACE: Red(1, ast.UnaryExpr),
		ADD: Red(1, ast.UnaryExpr),
		SUB: Red(1, ast.UnaryExpr),
		MUL: Red(1, ast.UnaryExpr),
		DIV: Red(1, ast.UnaryExpr),
		MOD: Red(1, ast.UnaryExpr),
		EQ: Red(1, ast.UnaryExpr),
		NEQ: Red(1, ast.UnaryExpr),
		LT: Red(1, ast.UnaryExpr),
		GT: Red(1, ast.UnaryExpr),
		LE: Red(1, ast.UnaryExpr),
		GE: Red(1, ast.UnaryExpr),
		COMMA: Red(1, ast.UnaryExpr),
		END: Red(1, ast.UnaryExpr),
	},
	19: {
		EOF: Acc(),
	},
	20: {
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	21: {
		USE: Red(1, ast.Item),
		LET: Red(1, ast.Item),
		IF: Red(1, ast.Item),
		RETURN: Red(1, ast.Item),
		IDENTIFIER: Red(1, ast.Item),
		INTEGER: Red(1, ast.Item),
		FLOATING: Red(1, ast.Item),
		STRING: Red(1, ast.Item),
		CHARACTER: Red(1, ast.Item),
		L_PAREN: Red(1, ast.Item),
		R_BRACE: Red(1, ast.Item),
		ADD: Red(1, ast.Item),
		SUB: Red(1, ast.Item),
		EOF: Red(1, ast.Item),
	},
	22: {
		R_PAREN: Red(1, ast.Literal),
		L_BRACE: Red(1, ast.Literal),
		ADD: Red(1, ast.Literal),
		SUB: Red(1, ast.Literal),
		MUL: Red(1, ast.Literal),
		DIV: Red(1, ast.Literal),
		MOD: Red(1, ast.Literal),
		EQ: Red(1, ast.Literal),
		NEQ: Red(1, ast.Literal),
		LT: Red(1, ast.Literal),
		GT: Red(1, ast.Literal),
		LE: Red(1, ast.Literal),
		GE: Red(1, ast.Literal),
		COMMA: Red(1, ast.Literal),
		END: Red(1, ast.Literal),
	},
	23: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	24: {
		IDENTIFIER: Sh(50),
	},
	25: {
		R_PAREN: Red(1, ast.BinaryExpr),
		L_BRACE: Red(1, ast.BinaryExpr),
		ADD: Red(1, ast.BinaryExpr),
		SUB: Red(1, ast.BinaryExpr),
		MUL: Red(1, ast.BinaryExpr),
		DIV: Red(1, ast.BinaryExpr),
		MOD: Red(1, ast.BinaryExpr),
		EQ: Red(1, ast.BinaryExpr),
		NEQ: Red(1, ast.BinaryExpr),
		LT: Red(1, ast.BinaryExpr),
		GT: Red(1, ast.BinaryExpr),
		LE: Red(1, ast.BinaryExpr),
		GE: Red(1, ast.BinaryExpr),
		COMMA: Red(1, ast.BinaryExpr),
		END: Red(1, ast.BinaryExpr),
	},
	26: {
		USE: Red(1, ast.Item),
		LET: Red(1, ast.Item),
		IF: Red(1, ast.Item),
		RETURN: Red(1, ast.Item),
		IDENTIFIER: Red(1, ast.Item),
		INTEGER: Red(1, ast.Item),
		FLOATING: Red(1, ast.Item),
		STRING: Red(1, ast.Item),
		CHARACTER: Red(1, ast.Item),
		L_PAREN: Red(1, ast.Item),
		R_BRACE: Red(1, ast.Item),
		ADD: Red(1, ast.Item),
		SUB: Red(1, ast.Item),
		EOF: Red(1, ast.Item),
	},
	27: {
		L_PAREN: Sh(42),
		R_PAREN: Red(1, ast.Ident),
		L_BRACE: Red(1, ast.Ident),
		ADD: Red(1, ast.Ident),
		SUB: Red(1, ast.Ident),
		MUL: Red(1, ast.Ident),
		DIV: Red(1, ast.Ident),
		MOD: Red(1, ast.Ident),
		EQ: Red(1, ast.Ident),
		NEQ: Red(1, ast.Ident),
		LT: Red(1, ast.Ident),
		GT: Red(1, ast.Ident),
		LE: Red(1, ast.Ident),
		GE: Red(1, ast.Ident),
		COMMA: Red(1, ast.Ident),
		END: Red(1, ast.Ident),
	},
	28: {
		R_PAREN: Red(2, ast.Unary),
		L_BRACE: Red(2, ast.Unary),
		ADD: Red(2, ast.Unary),
		SUB: Red(2, ast.Unary),
		MUL: Red(2, ast.Unary),
		DIV: Red(2, ast.Unary),
		MOD: Red(2, ast.Unary),
		EQ: Red(2, ast.Unary),
		NEQ: Red(2, ast.Unary),
		LT: Red(2, ast.Unary),
		GT: Red(2, ast.Unary),
		LE: Red(2, ast.Unary),
		GE: Red(2, ast.Unary),
		COMMA: Red(2, ast.Unary),
		END: Red(2, ast.Unary),
	},
	29: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	30: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	31: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	32: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	33: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	34: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	35: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	36: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	37: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	38: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	39: {
		IDENTIFIER: Sh(27),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	40: {
		USE: Red(2, ast.ExprStmt),
		LET: Red(2, ast.ExprStmt),
		IF: Red(2, ast.ExprStmt),
		RETURN: Red(2, ast.ExprStmt),
		IDENTIFIER: Red(2, ast.ExprStmt),
		INTEGER: Red(2, ast.ExprStmt),
		FLOATING: Red(2, ast.ExprStmt),
		STRING: Red(2, ast.ExprStmt),
		CHARACTER: Red(2, ast.ExprStmt),
		L_PAREN: Red(2, ast.ExprStmt),
		R_BRACE: Red(2, ast.ExprStmt),
		ADD: Red(2, ast.ExprStmt),
		SUB: Red(2, ast.ExprStmt),
		EOF: Red(2, ast.ExprStmt),
	},
	41: {
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	42: {
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		R_PAREN: Red(0, ast.Args),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	43: {
		L_BRACE: Sh(66),
	},
	44: {
		R_BRACE: Red(2, ast.Items),
		EOF: Red(2, ast.Items),
	},
	45: {
		EOF: Red(2, ast.Module),
	},
	46: {
		ASSIGN: Sh(67),
	},
	47: {
		R_PAREN: Sh(68),
	},
	48: {
		END: Sh(69),
	},
	49: {
		R_PAREN: Red(2, ast.Unary),
		L_BRACE: Red(2, ast.Unary),
		ADD: Red(2, ast.Unary),
		SUB: Red(2, ast.Unary),
		MUL: Red(2, ast.Unary),
		DIV: Red(2, ast.Unary),
		MOD: Red(2, ast.Unary),
		EQ: Red(2, ast.Unary),
		NEQ: Red(2, ast.Unary),
		LT: Red(2, ast.Unary),
		GT: Red(2, ast.Unary),
		LE: Red(2, ast.Unary),
		GE: Red(2, ast.Unary),
		COMMA: Red(2, ast.Unary),
		END: Red(2, ast.Unary),
	},
	50: {
		END: Sh(70),
	},
	51: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Red(3, ast.Binary),
		SUB: Red(3, ast.Binary),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	52: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Red(3, ast.Binary),
		SUB: Red(3, ast.Binary),
		MUL: Red(3, ast.Binary),
		DIV: Red(3, ast.Binary),
		MOD: Red(3, ast.Binary),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	53: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Sh(29),
		SUB: Sh(39),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Sh(35),
		GT: Sh(33),
		LE: Sh(34),
		GE: Sh(32),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	54: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Sh(29),
		SUB: Sh(39),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	55: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Sh(29),
		SUB: Sh(39),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	56: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Sh(29),
		SUB: Sh(39),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	57: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Sh(29),
		SUB: Sh(39),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	58: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Red(3, ast.Binary),
		SUB: Red(3, ast.Binary),
		MUL: Red(3, ast.Binary),
		DIV: Red(3, ast.Binary),
		MOD: Red(3, ast.Binary),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	59: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Red(3, ast.Binary),
		SUB: Red(3, ast.Binary),
		MUL: Red(3, ast.Binary),
		DIV: Red(3, ast.Binary),
		MOD: Red(3, ast.Binary),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	60: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Sh(29),
		SUB: Sh(39),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Sh(35),
		GT: Sh(33),
		LE: Sh(34),
		GE: Sh(32),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	61: {
		R_PAREN: Red(3, ast.Binary),
		L_BRACE: Red(3, ast.Binary),
		ADD: Red(3, ast.Binary),
		SUB: Red(3, ast.Binary),
		MUL: Sh(37),
		DIV: Sh(30),
		MOD: Sh(36),
		EQ: Red(3, ast.Binary),
		NEQ: Red(3, ast.Binary),
		LT: Red(3, ast.Binary),
		GT: Red(3, ast.Binary),
		LE: Red(3, ast.Binary),
		GE: Red(3, ast.Binary),
		COMMA: Red(3, ast.Binary),
		END: Red(3, ast.Binary),
	},
	62: {
		R_PAREN: Red(3, ast.Assign),
		L_BRACE: Red(3, ast.Assign),
		COMMA: Red(3, ast.Assign),
		END: Red(3, ast.Assign),
	},
	63: {
		R_PAREN: Sh(71),
	},
	64: {
		R_PAREN: Red(0, ast.ArgsTail),
		COMMA: Sh(73),
	},
	65: {
		USE: Red(3, ast.If),
		LET: Red(3, ast.If),
		IF: Red(3, ast.If),
		ELSE: Sh(74),
		RETURN: Red(3, ast.If),
		IDENTIFIER: Red(3, ast.If),
		INTEGER: Red(3, ast.If),
		FLOATING: Red(3, ast.If),
		STRING: Red(3, ast.If),
		CHARACTER: Red(3, ast.If),
		L_PAREN: Red(3, ast.If),
		R_BRACE: Red(3, ast.If),
		ADD: Red(3, ast.If),
		SUB: Red(3, ast.If),
		EOF: Red(3, ast.If),
	},
	66: {
		USE: Sh(24),
		LET: Sh(15),
		IF: Sh(10),
		RETURN: Sh(20),
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		R_BRACE: Red(0, ast.Items),
		ADD: Sh(1),
		SUB: Sh(23),
		EOF: Red(0, ast.Items),
	},
	67: {
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	68: {
		R_PAREN: Red(3, ast.Primary),
		L_BRACE: Red(3, ast.Primary),
		ADD: Red(3, ast.Primary),
		SUB: Red(3, ast.Primary),
		MUL: Red(3, ast.Primary),
		DIV: Red(3, ast.Primary),
		MOD: Red(3, ast.Primary),
		EQ: Red(3, ast.Primary),
		NEQ: Red(3, ast.Primary),
		LT: Red(3, ast.Primary),
		GT: Red(3, ast.Primary),
		LE: Red(3, ast.Primary),
		GE: Red(3, ast.Primary),
		COMMA: Red(3, ast.Primary),
		END: Red(3, ast.Primary),
	},
	69: {
		USE: Red(3, ast.Return),
		LET: Red(3, ast.Return),
		IF: Red(3, ast.Return),
		RETURN: Red(3, ast.Return),
		IDENTIFIER: Red(3, ast.Return),
		INTEGER: Red(3, ast.Return),
		FLOATING: Red(3, ast.Return),
		STRING: Red(3, ast.Return),
		CHARACTER: Red(3, ast.Return),
		L_PAREN: Red(3, ast.Return),
		R_BRACE: Red(3, ast.Return),
		ADD: Red(3, ast.Return),
		SUB: Red(3, ast.Return),
		EOF: Red(3, ast.Return),
	},
	70: {
		USE: Red(3, ast.Use),
		LET: Red(3, ast.Use),
		IF: Red(3, ast.Use),
		RETURN: Red(3, ast.Use),
		IDENTIFIER: Red(3, ast.Use),
		INTEGER: Red(3, ast.Use),
		FLOATING: Red(3, ast.Use),
		STRING: Red(3, ast.Use),
		CHARACTER: Red(3, ast.Use),
		L_PAREN: Red(3, ast.Use),
		R_BRACE: Red(3, ast.Use),
		ADD: Red(3, ast.Use),
		SUB: Red(3, ast.Use),
		EOF: Red(3, ast.Use),
	},
	71: {
		R_PAREN: Red(4, ast.Call),
		L_BRACE: Red(4, ast.Call),
		ADD: Red(4, ast.Call),
		SUB: Red(4, ast.Call),
		MUL: Red(4, ast.Call),
		DIV: Red(4, ast.Call),
		MOD: Red(4, ast.Call),
		EQ: Red(4, ast.Call),
		NEQ: Red(4, ast.Call),
		LT: Red(4, ast.Call),
		GT: Red(4, ast.Call),
		LE: Red(4, ast.Call),
		GE: Red(4, ast.Call),
		COMMA: Red(4, ast.Call),
		END: Red(4, ast.Call),
	},
	72: {
		R_PAREN: Red(2, ast.Args),
	},
	73: {
		IDENTIFIER: Sh(9),
		INTEGER: Sh(11),
		FLOATING: Sh(8),
		STRING: Sh(22),
		CHARACTER: Sh(4),
		L_PAREN: Sh(16),
		ADD: Sh(1),
		SUB: Sh(23),
	},
	74: {
		L_BRACE: Sh(66),
	},
	75: {
		R_BRACE: Sh(79),
	},
	76: {
		END: Sh(80),
	},
	77: {
		R_PAREN: Red(0, ast.ArgsTail),
		COMMA: Sh(73),
	},
	78: {
		USE: Red(5, ast.If),
		LET: Red(5, ast.If),
		IF: Red(5, ast.If),
		RETURN: Red(5, ast.If),
		IDENTIFIER: Red(5, ast.If),
		INTEGER: Red(5, ast.If),
		FLOATING: Red(5, ast.If),
		STRING: Red(5, ast.If),
		CHARACTER: Red(5, ast.If),
		L_PAREN: Red(5, ast.If),
		R_BRACE: Red(5, ast.If),
		ADD: Red(5, ast.If),
		SUB: Red(5, ast.If),
		EOF: Red(5, ast.If),
	},
	79: {
		USE: Red(3, ast.Block),
		LET: Red(3, ast.Block),
		IF: Red(3, ast.Block),
		ELSE: Red(3, ast.Block),
		RETURN: Red(3, ast.Block),
		IDENTIFIER: Red(3, ast.Block),
		INTEGER: Red(3, ast.Block),
		FLOATING: Red(3, ast.Block),
		STRING: Red(3, ast.Block),
		CHARACTER: Red(3, ast.Block),
		L_PAREN: Red(3, ast.Block),
		R_BRACE: Red(3, ast.Block),
		ADD: Red(3, ast.Block),
		SUB: Red(3, ast.Block),
		EOF: Red(3, ast.Block),
	},
	80: {
		USE: Red(5, ast.Let),
		LET: Red(5, ast.Let),
		IF: Red(5, ast.Let),
		RETURN: Red(5, ast.Let),
		IDENTIFIER: Red(5, ast.Let),
		INTEGER: Red(5, ast.Let),
		FLOATING: Red(5, ast.Let),
		STRING: Red(5, ast.Let),
		CHARACTER: Red(5, ast.Let),
		L_PAREN: Red(5, ast.Let),
		R_BRACE: Red(5, ast.Let),
		ADD: Red(5, ast.Let),
		SUB: Red(5, ast.Let),
		EOF: Red(5, ast.Let),
	},
	81: {
		R_PAREN: Red(3, ast.ArgsTail),
	},
}

var GotoMap = &map[int]map[ast.NodeType]int{
	0: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 6,
		ast.ExprStmt: 7,
		ast.IfStmt: 12,
		ast.Item: 13,
		ast.Items: 14,
		ast.LetStmt: 17,
		ast.Primary: 18,
		ast.Program: 19,
		ast.ReturnStmt: 21,
		ast.UnaryExpr: 25,
		ast.UseStmt: 26,
	},
	1: {
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 28,
	},
	10: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 43,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	13: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 6,
		ast.ExprStmt: 7,
		ast.IfStmt: 12,
		ast.Item: 13,
		ast.Items: 44,
		ast.LetStmt: 17,
		ast.Primary: 18,
		ast.ReturnStmt: 21,
		ast.UnaryExpr: 25,
		ast.UseStmt: 26,
	},
	16: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 47,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	20: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 48,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	23: {
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 49,
	},
	29: {
		ast.BinaryExpr: 51,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	30: {
		ast.BinaryExpr: 52,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	31: {
		ast.BinaryExpr: 53,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	32: {
		ast.BinaryExpr: 54,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	33: {
		ast.BinaryExpr: 55,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	34: {
		ast.BinaryExpr: 56,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	35: {
		ast.BinaryExpr: 57,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	36: {
		ast.BinaryExpr: 58,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	37: {
		ast.BinaryExpr: 59,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	38: {
		ast.BinaryExpr: 60,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	39: {
		ast.BinaryExpr: 61,
		ast.CallExpr: 5,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	41: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 62,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	42: {
		ast.Args: 63,
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 64,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	43: {
		ast.Block: 65,
	},
	64: {
		ast.ArgsTail: 72,
	},
	66: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 6,
		ast.ExprStmt: 7,
		ast.IfStmt: 12,
		ast.Item: 13,
		ast.Items: 75,
		ast.LetStmt: 17,
		ast.Primary: 18,
		ast.ReturnStmt: 21,
		ast.UnaryExpr: 25,
		ast.UseStmt: 26,
	},
	67: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 76,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	73: {
		ast.AssignExpr: 2,
		ast.BinaryExpr: 3,
		ast.CallExpr: 5,
		ast.Expr: 77,
		ast.Primary: 18,
		ast.UnaryExpr: 25,
	},
	74: {
		ast.Block: 78,
	},
	77: {
		ast.ArgsTail: 81,
	},
}
