// Code generated by fugu. DO NOT EDIT.
package action

import (
	"github.com/fugalang/fugu/internal/ast"
	"github.com/fugalang/fugu/internal/diagnostics/errors"
	. "github.com/fugalang/fugu/internal/token"
)

var ActionTokenCount int = 87

var Actions = []ActionStruct{
	Err(errors.Errors[6]),  // 0
	Err(errors.Errors[6]),  // 1
	Err(errors.Errors[6]),  // 2
	Err(errors.Errors[6]),  // 3
	Err(errors.Errors[6]),  // 4
	Red(2, ast.Items),      // 5
	Red(2, ast.Module),     // 6
	Sh(45),                 // 7
	Acc(),                  // 8
	Err(errors.Errors[6]),  // 9
	Red(3, ast.Block),      // 10
	Err(errors.Errors[6]),  // 11
	Err(errors.Errors[6]),  // 12
	Err(errors.Errors[6]),  // 13
	Err(errors.Errors[6]),  // 14
	Red(3, ast.Block),      // 15
	Err(errors.Errors[6]),  // 16
	Red(3, ast.Block),      // 17
	Red(3, ast.Block),      // 18
	Sh(46),                 // 19
	Sh(50),                 // 20
	Red(3, ast.Block),      // 21
	Red(3, ast.Block),      // 22
	Err(errors.Errors[6]),  // 23
	Red(3, ast.Block),      // 24
	Err(errors.Errors[6]),  // 25
	Red(3, ast.Block),      // 26
	Err(errors.Errors[6]),  // 27
	Err(errors.Errors[6]),  // 28
	Sh(11),                 // 29
	Err(errors.Errors[6]),  // 30
	Sh(8),                  // 31
	Sh(22),                 // 32
	Red(3, ast.Block),      // 33
	Err(errors.Errors[6]),  // 34
	Sh(4),                  // 35
	Sh(9),                  // 36
	Red(3, ast.Block),      // 37
	Red(3, ast.Block),      // 38
	Err(errors.Errors[6]),  // 39
	Err(errors.Errors[6]),  // 40
	Sh(42),                 // 41
	Red(1, ast.Ident),      // 42
	Red(1, ast.Ident),      // 43
	Red(2, ast.Items),      // 44
	Sh(66),                 // 45
	Red(3, ast.Block),      // 46
	Sh(41),                 // 47
	Sh(68),                 // 48
	Red(3, ast.Block),      // 49
	Red(3, ast.Assign),     // 50
	Red(3, ast.Assign),     // 51
	Sh(67),                 // 52
	Red(2, ast.Args),       // 53
	Red(1, ast.Ident),      // 54
	Red(1, ast.Ident),      // 55
	Red(1, ast.Ident),      // 56
	Red(1, ast.Ident),      // 57
	Red(1, ast.Ident),      // 58
	Red(1, ast.Ident),      // 59
	Sh(16),                 // 60
	Red(0, ast.Args),       // 61
	Red(0, ast.ArgsTail),   // 62
	Red(1, ast.Ident),      // 63
	Red(1, ast.Ident),      // 64
	Red(1, ast.Ident),      // 65
	Red(1, ast.Ident),      // 66
	Red(1, ast.Ident),      // 67
	Red(3, ast.Block),      // 68
	Red(3, ast.Block),      // 69
	Red(1, ast.Expr),       // 70
	Red(1, ast.Expr),       // 71
	Red(0, ast.ArgsTail),   // 72
	Sh(42),                 // 73
	Red(1, ast.Ident),      // 74
	Red(1, ast.Ident),      // 75
	Sh(79),                 // 76
	Sh(71),                 // 77
	Sh(66),                 // 78
	Red(3, ast.ArgsTail),   // 79
	Err(errors.Errors[6]),  // 80
	Err(errors.Errors[6]),  // 81
	Sh(23),                 // 82
	Sh(1),                  // 83
	Red(1, ast.Ident),      // 84
	Red(1, ast.Ident),      // 85
	Red(1, ast.Ident),      // 86
	Red(1, ast.Ident),      // 87
	Red(1, ast.Ident),      // 88
	Red(1, ast.Ident),      // 89
	Red(1, ast.Ident),      // 90
	Red(1, ast.Ident),      // 91
	Red(3, ast.Assign),     // 92
	Red(3, ast.Assign),     // 93
	Sh(69),                 // 94
	Red(1, ast.Ident),      // 95
	Red(1, ast.Ident),      // 96
	Red(1, ast.Ident),      // 97
	Red(1, ast.Ident),      // 98
	Red(1, ast.Ident),      // 99
	Sh(80),                 // 100
	Sh(40),                 // 101
	Sh(70),                 // 102
	Err(errors.Errors[6]),  // 103
	Err(errors.Errors[6]),  // 104
	Sh(73),                 // 105
	Red(3, ast.Binary),     // 106
	Red(3, ast.Binary),     // 107
	Err(errors.Errors[6]),  // 108
	Err(errors.Errors[6]),  // 109
	Err(errors.Errors[6]),  // 110
	Err(errors.Errors[6]),  // 111
	Red(1, ast.Expr),       // 112
	Red(1, ast.Expr),       // 113
	Err(errors.Errors[6]),  // 114
	Sh(73),                 // 115
	Red(1, ast.Ident),      // 116
	Red(1, ast.Ident),      // 117
	Red(3, ast.Binary),     // 118
	Red(3, ast.Binary),     // 119
	Red(3, ast.Binary),     // 120
	Red(3, ast.Binary),     // 121
	Red(3, ast.Binary),     // 122
	Red(3, ast.Binary),     // 123
	Err(errors.Errors[6]),  // 124
	Err(errors.Errors[6]),  // 125
	Err(errors.Errors[6]),  // 126
	Red(3, ast.Binary),     // 127
	Red(3, ast.Binary),     // 128
	Red(3, ast.Binary),     // 129
	Red(3, ast.Binary),     // 130
	Red(3, ast.Binary),     // 131
	Err(errors.Errors[6]),  // 132
	Err(errors.Errors[6]),  // 133
	Err(errors.Errors[6]),  // 134
	Err(errors.Errors[6]),  // 135
	Err(errors.Errors[6]),  // 136
	Err(errors.Errors[6]),  // 137
	Red(3, ast.Binary),     // 138
	Red(3, ast.Binary),     // 139
	Err(errors.Errors[6]),  // 140
	Err(errors.Errors[6]),  // 141
	Err(errors.Errors[6]),  // 142
	Err(errors.Errors[6]),  // 143
	Err(errors.Errors[6]),  // 144
	Err(errors.Errors[6]),  // 145
	Err(errors.Errors[6]),  // 146
	Err(errors.Errors[6]),  // 147
	Red(3, ast.Binary),     // 148
	Red(3, ast.Binary),     // 149
	Red(3, ast.Binary),     // 150
	Red(3, ast.Binary),     // 151
	Red(3, ast.Binary),     // 152
	Red(3, ast.Binary),     // 153
	Red(3, ast.Binary),     // 154
	Red(3, ast.Binary),     // 155
	Err(errors.Errors[6]),  // 156
	Err(errors.Errors[6]),  // 157
	Err(errors.Errors[6]),  // 158
	Sh(39),                 // 159
	Sh(29),                 // 160
	Sh(37),                 // 161
	Sh(30),                 // 162
	Sh(36),                 // 163
	Err(errors.Errors[6]),  // 164
	Err(errors.Errors[6]),  // 165
	Err(errors.Errors[6]),  // 166
	Err(errors.Errors[6]),  // 167
	Err(errors.Errors[6]),  // 168
	Err(errors.Errors[6]),  // 169
	Red(1, ast.Literal),    // 170
	Red(1, ast.Literal),    // 171
	Err(errors.Errors[6]),  // 172
	Err(errors.Errors[6]),  // 173
	Err(errors.Errors[6]),  // 174
	Err(errors.Errors[6]),  // 175
	Err(errors.Errors[6]),  // 176
	Err(errors.Errors[6]),  // 177
	Err(errors.Errors[6]),  // 178
	Err(errors.Errors[6]),  // 179
	Red(3, ast.Binary),     // 180
	Red(3, ast.Binary),     // 181
	Red(1, ast.Literal),    // 182
	Red(1, ast.Literal),    // 183
	Red(1, ast.Literal),    // 184
	Red(1, ast.Literal),    // 185
	Red(1, ast.Literal),    // 186
	Red(1, ast.Literal),    // 187
	Err(errors.Errors[6]),  // 188
	Err(errors.Errors[6]),  // 189
	Err(errors.Errors[6]),  // 190
	Red(1, ast.Literal),    // 191
	Red(1, ast.Literal),    // 192
	Red(1, ast.Literal),    // 193
	Red(1, ast.Literal),    // 194
	Red(1, ast.Literal),    // 195
	Err(errors.Errors[6]),  // 196
	Err(errors.Errors[6]),  // 197
	Err(errors.Errors[6]),  // 198
	Err(errors.Errors[6]),  // 199
	Err(errors.Errors[6]),  // 200
	Err(errors.Errors[6]),  // 201
	Red(1, ast.Primary),    // 202
	Red(1, ast.Primary),    // 203
	Err(errors.Errors[6]),  // 204
	Err(errors.Errors[6]),  // 205
	Err(errors.Errors[6]),  // 206
	Err(errors.Errors[6]),  // 207
	Err(errors.Errors[6]),  // 208
	Err(errors.Errors[6]),  // 209
	Err(errors.Errors[6]),  // 210
	Err(errors.Errors[6]),  // 211
	Red(1, ast.Literal),    // 212
	Red(1, ast.Literal),    // 213
	Red(1, ast.Primary),    // 214
	Red(1, ast.Primary),    // 215
	Red(1, ast.Primary),    // 216
	Red(1, ast.Primary),    // 217
	Red(1, ast.Primary),    // 218
	Red(1, ast.Primary),    // 219
	Err(errors.Errors[6]),  // 220
	Err(errors.Errors[6]),  // 221
	Err(errors.Errors[6]),  // 222
	Red(1, ast.Primary),    // 223
	Red(1, ast.Primary),    // 224
	Red(1, ast.Primary),    // 225
	Red(1, ast.Primary),    // 226
	Red(1, ast.Primary),    // 227
	Err(errors.Errors[6]),  // 228
	Err(errors.Errors[6]),  // 229
	Err(errors.Errors[6]),  // 230
	Err(errors.Errors[6]),  // 231
	Err(errors.Errors[6]),  // 232
	Err(errors.Errors[6]),  // 233
	Red(2, ast.Unary),      // 234
	Red(2, ast.Unary),      // 235
	Err(errors.Errors[6]),  // 236
	Err(errors.Errors[6]),  // 237
	Err(errors.Errors[6]),  // 238
	Err(errors.Errors[6]),  // 239
	Err(errors.Errors[6]),  // 240
	Err(errors.Errors[6]),  // 241
	Err(errors.Errors[6]),  // 242
	Err(errors.Errors[6]),  // 243
	Red(1, ast.Primary),    // 244
	Red(1, ast.Primary),    // 245
	Red(2, ast.Unary),      // 246
	Red(2, ast.Unary),      // 247
	Red(2, ast.Unary),      // 248
	Red(2, ast.Unary),      // 249
	Red(2, ast.Unary),      // 250
	Red(2, ast.Unary),      // 251
	Err(errors.Errors[6]),  // 252
	Err(errors.Errors[6]),  // 253
	Err(errors.Errors[6]),  // 254
	Red(2, ast.Unary),      // 255
	Red(2, ast.Unary),      // 256
	Red(2, ast.Unary),      // 257
	Red(2, ast.Unary),      // 258
	Red(2, ast.Unary),      // 259
	Err(errors.Errors[6]),  // 260
	Err(errors.Errors[6]),  // 261
	Err(errors.Errors[6]),  // 262
	Err(errors.Errors[6]),  // 263
	Err(errors.Errors[6]),  // 264
	Err(errors.Errors[6]),  // 265
	Red(3, ast.Binary),     // 266
	Red(3, ast.Binary),     // 267
	Err(errors.Errors[6]),  // 268
	Err(errors.Errors[6]),  // 269
	Err(errors.Errors[6]),  // 270
	Err(errors.Errors[6]),  // 271
	Err(errors.Errors[6]),  // 272
	Err(errors.Errors[6]),  // 273
	Err(errors.Errors[6]),  // 274
	Err(errors.Errors[6]),  // 275
	Red(2, ast.Unary),      // 276
	Red(2, ast.Unary),      // 277
	Red(3, ast.Binary),     // 278
	Red(3, ast.Binary),     // 279
	Red(3, ast.Binary),     // 280
	Red(3, ast.Binary),     // 281
	Red(3, ast.Binary),     // 282
	Red(3, ast.Binary),     // 283
	Err(errors.Errors[6]),  // 284
	Err(errors.Errors[6]),  // 285
	Err(errors.Errors[6]),  // 286
	Red(3, ast.Binary),     // 287
	Red(3, ast.Binary),     // 288
	Sh(37),                 // 289
	Sh(30),                 // 290
	Sh(36),                 // 291
	Err(errors.Errors[6]),  // 292
	Err(errors.Errors[6]),  // 293
	Err(errors.Errors[6]),  // 294
	Err(errors.Errors[6]),  // 295
	Err(errors.Errors[6]),  // 296
	Err(errors.Errors[6]),  // 297
	Red(1, ast.Literal),    // 298
	Red(1, ast.Literal),    // 299
	Err(errors.Errors[6]),  // 300
	Err(errors.Errors[6]),  // 301
	Err(errors.Errors[6]),  // 302
	Err(errors.Errors[6]),  // 303
	Err(errors.Errors[6]),  // 304
	Err(errors.Errors[6]),  // 305
	Err(errors.Errors[6]),  // 306
	Err(errors.Errors[6]),  // 307
	Red(3, ast.Binary),     // 308
	Red(3, ast.Binary),     // 309
	Red(1, ast.Literal),    // 310
	Red(1, ast.Literal),    // 311
	Red(1, ast.Literal),    // 312
	Red(1, ast.Literal),    // 313
	Red(1, ast.Literal),    // 314
	Red(1, ast.Literal),    // 315
	Err(errors.Errors[6]),  // 316
	Err(errors.Errors[6]),  // 317
	Err(errors.Errors[6]),  // 318
	Red(1, ast.Literal),    // 319
	Red(1, ast.Literal),    // 320
	Red(1, ast.Literal),    // 321
	Red(1, ast.Literal),    // 322
	Red(1, ast.Literal),    // 323
	Err(errors.Errors[6]),  // 324
	Err(errors.Errors[6]),  // 325
	Err(errors.Errors[6]),  // 326
	Err(errors.Errors[6]),  // 327
	Err(errors.Errors[6]),  // 328
	Err(errors.Errors[6]),  // 329
	Red(4, ast.Call),       // 330
	Red(4, ast.Call),       // 331
	Err(errors.Errors[6]),  // 332
	Err(errors.Errors[6]),  // 333
	Err(errors.Errors[6]),  // 334
	Err(errors.Errors[6]),  // 335
	Err(errors.Errors[6]),  // 336
	Err(errors.Errors[6]),  // 337
	Err(errors.Errors[6]),  // 338
	Err(errors.Errors[6]),  // 339
	Red(1, ast.Literal),    // 340
	Red(1, ast.Literal),    // 341
	Red(4, ast.Call),       // 342
	Red(4, ast.Call),       // 343
	Red(4, ast.Call),       // 344
	Red(4, ast.Call),       // 345
	Red(4, ast.Call),       // 346
	Red(4, ast.Call),       // 347
	Err(errors.Errors[6]),  // 348
	Err(errors.Errors[6]),  // 349
	Err(errors.Errors[6]),  // 350
	Red(4, ast.Call),       // 351
	Red(4, ast.Call),       // 352
	Red(4, ast.Call),       // 353
	Red(4, ast.Call),       // 354
	Red(4, ast.Call),       // 355
	Err(errors.Errors[6]),  // 356
	Err(errors.Errors[6]),  // 357
	Err(errors.Errors[6]),  // 358
	Err(errors.Errors[6]),  // 359
	Err(errors.Errors[6]),  // 360
	Err(errors.Errors[6]),  // 361
	Red(1, ast.Literal),    // 362
	Red(1, ast.Literal),    // 363
	Err(errors.Errors[6]),  // 364
	Err(errors.Errors[6]),  // 365
	Err(errors.Errors[6]),  // 366
	Err(errors.Errors[6]),  // 367
	Err(errors.Errors[6]),  // 368
	Err(errors.Errors[6]),  // 369
	Err(errors.Errors[6]),  // 370
	Err(errors.Errors[6]),  // 371
	Red(4, ast.Call),       // 372
	Red(4, ast.Call),       // 373
	Red(1, ast.Literal),    // 374
	Red(1, ast.Literal),    // 375
	Red(1, ast.Literal),    // 376
	Red(1, ast.Literal),    // 377
	Red(1, ast.Literal),    // 378
	Red(1, ast.Literal),    // 379
	Err(errors.Errors[6]),  // 380
	Err(errors.Errors[6]),  // 381
	Err(errors.Errors[6]),  // 382
	Red(1, ast.Literal),    // 383
	Red(1, ast.Literal),    // 384
	Red(1, ast.Literal),    // 385
	Red(1, ast.Literal),    // 386
	Red(1, ast.Literal),    // 387
	Err(errors.Errors[6]),  // 388
	Err(errors.Errors[6]),  // 389
	Err(errors.Errors[6]),  // 390
	Err(errors.Errors[6]),  // 391
	Err(errors.Errors[6]),  // 392
	Err(errors.Errors[6]),  // 393
	Red(3, ast.Binary),     // 394
	Red(3, ast.Binary),     // 395
	Err(errors.Errors[6]),  // 396
	Err(errors.Errors[6]),  // 397
	Err(errors.Errors[6]),  // 398
	Err(errors.Errors[6]),  // 399
	Err(errors.Errors[6]),  // 400
	Err(errors.Errors[6]),  // 401
	Err(errors.Errors[6]),  // 402
	Err(errors.Errors[6]),  // 403
	Red(1, ast.Literal),    // 404
	Red(1, ast.Literal),    // 405
	Red(3, ast.Binary),     // 406
	Red(3, ast.Binary),     // 407
	Red(3, ast.Binary),     // 408
	Red(3, ast.Binary),     // 409
	Red(3, ast.Binary),     // 410
	Red(3, ast.Binary),     // 411
	Err(errors.Errors[6]),  // 412
	Err(errors.Errors[6]),  // 413
	Err(errors.Errors[6]),  // 414
	Red(3, ast.Binary),     // 415
	Red(3, ast.Binary),     // 416
	Red(3, ast.Binary),     // 417
	Red(3, ast.Binary),     // 418
	Red(3, ast.Binary),     // 419
	Err(errors.Errors[6]),  // 420
	Err(errors.Errors[6]),  // 421
	Err(errors.Errors[6]),  // 422
	Err(errors.Errors[6]),  // 423
	Err(errors.Errors[6]),  // 424
	Err(errors.Errors[6]),  // 425
	Red(3, ast.Binary),     // 426
	Red(3, ast.Binary),     // 427
	Err(errors.Errors[6]),  // 428
	Err(errors.Errors[6]),  // 429
	Err(errors.Errors[6]),  // 430
	Err(errors.Errors[6]),  // 431
	Err(errors.Errors[6]),  // 432
	Err(errors.Errors[6]),  // 433
	Err(errors.Errors[6]),  // 434
	Err(errors.Errors[6]),  // 435
	Red(3, ast.Binary),     // 436
	Red(3, ast.Binary),     // 437
	Red(3, ast.Binary),     // 438
	Red(3, ast.Binary),     // 439
	Sh(34),                 // 440
	Sh(32),                 // 441
	Sh(35),                 // 442
	Sh(33),                 // 443
	Err(errors.Errors[6]),  // 444
	Err(errors.Errors[6]),  // 445
	Err(errors.Errors[6]),  // 446
	Sh(39),                 // 447
	Sh(29),                 // 448
	Sh(37),                 // 449
	Sh(30),                 // 450
	Sh(36),                 // 451
	Err(errors.Errors[6]),  // 452
	Err(errors.Errors[6]),  // 453
	Err(errors.Errors[6]),  // 454
	Err(errors.Errors[6]),  // 455
	Err(errors.Errors[6]),  // 456
	Err(errors.Errors[6]),  // 457
	Red(3, ast.Binary),     // 458
	Red(3, ast.Binary),     // 459
	Err(errors.Errors[6]),  // 460
	Err(errors.Errors[6]),  // 461
	Err(errors.Errors[6]),  // 462
	Err(errors.Errors[6]),  // 463
	Err(errors.Errors[6]),  // 464
	Err(errors.Errors[6]),  // 465
	Err(errors.Errors[6]),  // 466
	Err(errors.Errors[6]),  // 467
	Red(3, ast.Binary),     // 468
	Red(3, ast.Binary),     // 469
	Red(3, ast.Binary),     // 470
	Red(3, ast.Binary),     // 471
	Red(3, ast.Binary),     // 472
	Red(3, ast.Binary),     // 473
	Red(3, ast.Binary),     // 474
	Red(3, ast.Binary),     // 475
	Err(errors.Errors[6]),  // 476
	Err(errors.Errors[6]),  // 477
	Err(errors.Errors[6]),  // 478
	Sh(39),                 // 479
	Sh(29),                 // 480
	Sh(37),                 // 481
	Sh(30),                 // 482
	Sh(36),                 // 483
	Err(errors.Errors[6]),  // 484
	Err(errors.Errors[6]),  // 485
	Err(errors.Errors[6]),  // 486
	Err(errors.Errors[6]),  // 487
	Err(errors.Errors[6]),  // 488
	Err(errors.Errors[6]),  // 489
	Red(2, ast.Unary),      // 490
	Red(2, ast.Unary),      // 491
	Err(errors.Errors[6]),  // 492
	Err(errors.Errors[6]),  // 493
	Err(errors.Errors[6]),  // 494
	Err(errors.Errors[6]),  // 495
	Err(errors.Errors[6]),  // 496
	Err(errors.Errors[6]),  // 497
	Err(errors.Errors[6]),  // 498
	Err(errors.Errors[6]),  // 499
	Red(3, ast.Binary),     // 500
	Red(3, ast.Binary),     // 501
	Red(2, ast.Unary),      // 502
	Red(2, ast.Unary),      // 503
	Red(2, ast.Unary),      // 504
	Red(2, ast.Unary),      // 505
	Red(2, ast.Unary),      // 506
	Red(2, ast.Unary),      // 507
	Err(errors.Errors[6]),  // 508
	Err(errors.Errors[6]),  // 509
	Err(errors.Errors[6]),  // 510
	Red(2, ast.Unary),      // 511
	Red(2, ast.Unary),      // 512
	Red(2, ast.Unary),      // 513
	Red(2, ast.Unary),      // 514
	Red(2, ast.Unary),      // 515
	Err(errors.Errors[6]),  // 516
	Err(errors.Errors[6]),  // 517
	Err(errors.Errors[6]),  // 518
	Err(errors.Errors[6]),  // 519
	Err(errors.Errors[6]),  // 520
	Err(errors.Errors[6]),  // 521
	Red(3, ast.Primary),    // 522
	Red(3, ast.Primary),    // 523
	Err(errors.Errors[6]),  // 524
	Err(errors.Errors[6]),  // 525
	Err(errors.Errors[6]),  // 526
	Err(errors.Errors[6]),  // 527
	Err(errors.Errors[6]),  // 528
	Err(errors.Errors[6]),  // 529
	Err(errors.Errors[6]),  // 530
	Err(errors.Errors[6]),  // 531
	Red(2, ast.Unary),      // 532
	Red(2, ast.Unary),      // 533
	Red(3, ast.Primary),    // 534
	Red(3, ast.Primary),    // 535
	Red(3, ast.Primary),    // 536
	Red(3, ast.Primary),    // 537
	Red(3, ast.Primary),    // 538
	Red(3, ast.Primary),    // 539
	Err(errors.Errors[6]),  // 540
	Err(errors.Errors[6]),  // 541
	Err(errors.Errors[6]),  // 542
	Red(3, ast.Primary),    // 543
	Red(3, ast.Primary),    // 544
	Red(3, ast.Primary),    // 545
	Red(3, ast.Primary),    // 546
	Red(3, ast.Primary),    // 547
	Err(errors.Errors[6]),  // 548
	Err(errors.Errors[6]),  // 549
	Err(errors.Errors[6]),  // 550
	Err(errors.Errors[6]),  // 551
	Err(errors.Errors[6]),  // 552
	Err(errors.Errors[6]),  // 553
	Red(3, ast.Binary),     // 554
	Red(3, ast.Binary),     // 555
	Err(errors.Errors[6]),  // 556
	Err(errors.Errors[6]),  // 557
	Err(errors.Errors[6]),  // 558
	Err(errors.Errors[6]),  // 559
	Err(errors.Errors[6]),  // 560
	Err(errors.Errors[6]),  // 561
	Err(errors.Errors[6]),  // 562
	Err(errors.Errors[6]),  // 563
	Red(3, ast.Primary),    // 564
	Red(3, ast.Primary),    // 565
	Red(3, ast.Binary),     // 566
	Red(3, ast.Binary),     // 567
	Red(3, ast.Binary),     // 568
	Red(3, ast.Binary),     // 569
	Red(3, ast.Binary),     // 570
	Red(3, ast.Binary),     // 571
	Err(errors.Errors[6]),  // 572
	Err(errors.Errors[6]),  // 573
	Err(errors.Errors[6]),  // 574
	Sh(39),                 // 575
	Sh(29),                 // 576
	Sh(37),                 // 577
	Sh(30),                 // 578
	Sh(36),                 // 579
	Err(errors.Errors[6]),  // 580
	Err(errors.Errors[6]),  // 581
	Err(errors.Errors[6]),  // 582
	Err(errors.Errors[6]),  // 583
	Err(errors.Errors[6]),  // 584
	Err(errors.Errors[6]),  // 585
	Red(3, ast.Binary),     // 586
	Red(3, ast.Binary),     // 587
	Err(errors.Errors[6]),  // 588
	Err(errors.Errors[6]),  // 589
	Err(errors.Errors[6]),  // 590
	Err(errors.Errors[6]),  // 591
	Err(errors.Errors[6]),  // 592
	Err(errors.Errors[6]),  // 593
	Err(errors.Errors[6]),  // 594
	Err(errors.Errors[6]),  // 595
	Red(3, ast.Binary),     // 596
	Red(3, ast.Binary),     // 597
	Red(3, ast.Binary),     // 598
	Red(3, ast.Binary),     // 599
	Red(3, ast.Binary),     // 600
	Red(3, ast.Binary),     // 601
	Red(3, ast.Binary),     // 602
	Red(3, ast.Binary),     // 603
	Err(errors.Errors[6]),  // 604
	Err(errors.Errors[6]),  // 605
	Err(errors.Errors[6]),  // 606
	Sh(39),                 // 607
	Sh(29),                 // 608
	Sh(37),                 // 609
	Sh(30),                 // 610
	Sh(36),                 // 611
	Err(errors.Errors[6]),  // 612
	Err(errors.Errors[6]),  // 613
	Err(errors.Errors[6]),  // 614
	Err(errors.Errors[6]),  // 615
	Err(errors.Errors[6]),  // 616
	Err(errors.Errors[6]),  // 617
	Red(3, ast.Binary),     // 618
	Red(3, ast.Binary),     // 619
	Err(errors.Errors[6]),  // 620
	Err(errors.Errors[6]),  // 621
	Err(errors.Errors[6]),  // 622
	Err(errors.Errors[6]),  // 623
	Err(errors.Errors[6]),  // 624
	Err(errors.Errors[6]),  // 625
	Err(errors.Errors[6]),  // 626
	Err(errors.Errors[6]),  // 627
	Red(3, ast.Binary),     // 628
	Red(3, ast.Binary),     // 629
	Red(3, ast.Binary),     // 630
	Red(3, ast.Binary),     // 631
	Red(3, ast.Binary),     // 632
	Red(3, ast.Binary),     // 633
	Red(3, ast.Binary),     // 634
	Red(3, ast.Binary),     // 635
	Err(errors.Errors[6]),  // 636
	Err(errors.Errors[6]),  // 637
	Err(errors.Errors[6]),  // 638
	Red(3, ast.Binary),     // 639
	Red(3, ast.Binary),     // 640
	Red(3, ast.Binary),     // 641
	Red(3, ast.Binary),     // 642
	Red(3, ast.Binary),     // 643
	Err(errors.Errors[6]),  // 644
	Err(errors.Errors[6]),  // 645
	Err(errors.Errors[6]),  // 646
	Err(errors.Errors[6]),  // 647
	Err(errors.Errors[6]),  // 648
	Err(errors.Errors[6]),  // 649
	Red(1, ast.AssignExpr), // 650
	Red(1, ast.AssignExpr), // 651
	Err(errors.Errors[6]),  // 652
	Err(errors.Errors[6]),  // 653
	Err(errors.Errors[6]),  // 654
	Err(errors.Errors[6]),  // 655
	Err(errors.Errors[6]),  // 656
	Err(errors.Errors[6]),  // 657
	Err(errors.Errors[6]),  // 658
	Err(errors.Errors[6]),  // 659
	Red(3, ast.Binary),     // 660
	Red(3, ast.Binary),     // 661
	Sh(31),                 // 662
	Sh(38),                 // 663
	Sh(34),                 // 664
	Sh(32),                 // 665
	Sh(35),                 // 666
	Sh(33),                 // 667
	Err(errors.Errors[6]),  // 668
	Err(errors.Errors[6]),  // 669
	Err(errors.Errors[6]),  // 670
	Sh(39),                 // 671
	Sh(29),                 // 672
	Sh(37),                 // 673
	Sh(30),                 // 674
	Sh(36),                 // 675
	Err(errors.Errors[6]),  // 676
	Err(errors.Errors[6]),  // 677
	Err(errors.Errors[6]),  // 678
	Err(errors.Errors[6]),  // 679
	Err(errors.Errors[6]),  // 680
	Err(errors.Errors[6]),  // 681
	Red(1, ast.UnaryExpr),  // 682
	Red(1, ast.UnaryExpr),  // 683
	Err(errors.Errors[6]),  // 684
	Err(errors.Errors[6]),  // 685
	Err(errors.Errors[6]),  // 686
	Err(errors.Errors[6]),  // 687
	Err(errors.Errors[6]),  // 688
	Err(errors.Errors[6]),  // 689
	Err(errors.Errors[6]),  // 690
	Err(errors.Errors[6]),  // 691
	Red(1, ast.AssignExpr), // 692
	Red(1, ast.AssignExpr), // 693
	Red(1, ast.UnaryExpr),  // 694
	Red(1, ast.UnaryExpr),  // 695
	Red(1, ast.UnaryExpr),  // 696
	Red(1, ast.UnaryExpr),  // 697
	Red(1, ast.UnaryExpr),  // 698
	Red(1, ast.UnaryExpr),  // 699
	Err(errors.Errors[6]),  // 700
	Err(errors.Errors[6]),  // 701
	Err(errors.Errors[6]),  // 702
	Red(1, ast.UnaryExpr),  // 703
	Red(1, ast.UnaryExpr),  // 704
	Red(1, ast.UnaryExpr),  // 705
	Red(1, ast.UnaryExpr),  // 706
	Red(1, ast.UnaryExpr),  // 707
	Err(errors.Errors[6]),  // 708
	Err(errors.Errors[6]),  // 709
	Err(errors.Errors[6]),  // 710
	Err(errors.Errors[6]),  // 711
	Err(errors.Errors[6]),  // 712
	Err(errors.Errors[6]),  // 713
	Red(1, ast.BinaryExpr), // 714
	Red(1, ast.BinaryExpr), // 715
	Err(errors.Errors[6]),  // 716
	Err(errors.Errors[6]),  // 717
	Err(errors.Errors[6]),  // 718
	Err(errors.Errors[6]),  // 719
	Err(errors.Errors[6]),  // 720
	Err(errors.Errors[6]),  // 721
	Err(errors.Errors[6]),  // 722
	Err(errors.Errors[6]),  // 723
	Red(1, ast.UnaryExpr),  // 724
	Red(1, ast.UnaryExpr),  // 725
	Red(1, ast.BinaryExpr), // 726
	Red(1, ast.BinaryExpr), // 727
	Red(1, ast.BinaryExpr), // 728
	Red(1, ast.BinaryExpr), // 729
	Red(1, ast.BinaryExpr), // 730
	Red(1, ast.BinaryExpr), // 731
	Err(errors.Errors[6]),  // 732
	Err(errors.Errors[6]),  // 733
	Err(errors.Errors[6]),  // 734
	Red(1, ast.BinaryExpr), // 735
	Red(1, ast.BinaryExpr), // 736
	Red(1, ast.BinaryExpr), // 737
	Red(1, ast.BinaryExpr), // 738
	Red(1, ast.BinaryExpr), // 739
	Err(errors.Errors[6]),  // 740
	Err(errors.Errors[6]),  // 741
	Sh(11),                 // 742
	Err(errors.Errors[6]),  // 743
	Sh(8),                  // 744
	Sh(22),                 // 745
	Err(errors.Errors[6]),  // 746
	Red(3, ast.If),         // 747
	Sh(4),                  // 748
	Sh(9),                  // 749
	Err(errors.Errors[6]),  // 750
	Err(errors.Errors[6]),  // 751
	Red(3, ast.If),         // 752
	Err(errors.Errors[6]),  // 753
	Red(3, ast.If),         // 754
	Red(3, ast.If),         // 755
	Red(1, ast.BinaryExpr), // 756
	Red(1, ast.BinaryExpr), // 757
	Red(3, ast.If),         // 758
	Red(3, ast.If),         // 759
	Err(errors.Errors[6]),  // 760
	Red(3, ast.If),         // 761
	Err(errors.Errors[6]),  // 762
	Red(3, ast.If),         // 763
	Err(errors.Errors[6]),  // 764
	Err(errors.Errors[6]),  // 765
	Err(errors.Errors[6]),  // 766
	Err(errors.Errors[6]),  // 767
	Err(errors.Errors[6]),  // 768
	Err(errors.Errors[6]),  // 769
	Red(3, ast.If),         // 770
	Err(errors.Errors[6]),  // 771
	Err(errors.Errors[6]),  // 772
	Sh(16),                 // 773
	Red(3, ast.If),         // 774
	Sh(74),                 // 775
	Red(3, ast.Binary),     // 776
	Red(3, ast.Binary),     // 777
	Err(errors.Errors[6]),  // 778
	Err(errors.Errors[6]),  // 779
	Err(errors.Errors[6]),  // 780
	Err(errors.Errors[6]),  // 781
	Err(errors.Errors[6]),  // 782
	Red(3, ast.If),         // 783
	Err(errors.Errors[6]),  // 784
	Err(errors.Errors[6]),  // 785
	Red(3, ast.If),         // 786
	Err(errors.Errors[6]),  // 787
	Red(3, ast.Binary),     // 788
	Red(3, ast.Binary),     // 789
	Red(3, ast.Binary),     // 790
	Red(3, ast.Binary),     // 791
	Red(3, ast.Binary),     // 792
	Red(3, ast.Binary),     // 793
	Err(errors.Errors[6]),  // 794
	Sh(23),                 // 795
	Sh(1),                  // 796
	Red(3, ast.Binary),     // 797
	Red(3, ast.Binary),     // 798
	Sh(37),                 // 799
	Sh(30),                 // 800
	Sh(36),                 // 801
	Err(errors.Errors[6]),  // 802
	Err(errors.Errors[6]),  // 803
	Err(errors.Errors[6]),  // 804
	Red(3, ast.If),         // 805
	Red(3, ast.If),         // 806
	Err(errors.Errors[6]),  // 807
	Red(1, ast.Literal),    // 808
	Red(1, ast.Literal),    // 809
	Err(errors.Errors[6]),  // 810
	Err(errors.Errors[6]),  // 811
	Err(errors.Errors[6]),  // 812
	Err(errors.Errors[6]),  // 813
	Err(errors.Errors[6]),  // 814
	Err(errors.Errors[6]),  // 815
	Err(errors.Errors[6]),  // 816
	Err(errors.Errors[6]),  // 817
	Red(3, ast.Binary),     // 818
	Red(3, ast.Binary),     // 819
	Red(1, ast.Literal),    // 820
	Red(1, ast.Literal),    // 821
	Red(1, ast.Literal),    // 822
	Red(1, ast.Literal),    // 823
	Red(1, ast.Literal),    // 824
	Red(1, ast.Literal),    // 825
	Err(errors.Errors[6]),  // 826
	Err(errors.Errors[6]),  // 827
	Err(errors.Errors[6]),  // 828
	Red(1, ast.Literal),    // 829
	Red(1, ast.Literal),    // 830
	Red(1, ast.Literal),    // 831
	Red(1, ast.Literal),    // 832
	Red(1, ast.Literal),    // 833
	Err(errors.Errors[6]),  // 834
	Err(errors.Errors[6]),  // 835
	Err(errors.Errors[6]),  // 836
	Err(errors.Errors[6]),  // 837
	Err(errors.Errors[6]),  // 838
	Err(errors.Errors[6]),  // 839
	Red(3, ast.Binary),     // 840
	Red(3, ast.Binary),     // 841
	Err(errors.Errors[6]),  // 842
	Err(errors.Errors[6]),  // 843
	Err(errors.Errors[6]),  // 844
	Err(errors.Errors[6]),  // 845
	Err(errors.Errors[6]),  // 846
	Err(errors.Errors[6]),  // 847
	Err(errors.Errors[6]),  // 848
	Err(errors.Errors[6]),  // 849
	Red(1, ast.Literal),    // 850
	Red(1, ast.Literal),    // 851
	Red(3, ast.Binary),     // 852
	Red(3, ast.Binary),     // 853
	Sh(34),                 // 854
	Sh(32),                 // 855
	Sh(35),                 // 856
	Sh(33),                 // 857
	Err(errors.Errors[6]),  // 858
	Err(errors.Errors[6]),  // 859
	Err(errors.Errors[6]),  // 860
	Sh(39),                 // 861
	Sh(29),                 // 862
	Sh(37),                 // 863
	Sh(30),                 // 864
	Sh(36),                 // 865
	Err(errors.Errors[6]),  // 866
	Err(errors.Errors[6]),  // 867
	Err(errors.Errors[6]),  // 868
	Err(errors.Errors[6]),  // 869
	Err(errors.Errors[6]),  // 870
	Err(errors.Errors[6]),  // 871
	Err(errors.Errors[6]),  // 872
	Red(1, ast.Item),       // 873
	Err(errors.Errors[6]),  // 874
	Err(errors.Errors[6]),  // 875
	Err(errors.Errors[6]),  // 876
	Err(errors.Errors[6]),  // 877
	Red(1, ast.Item),       // 878
	Err(errors.Errors[6]),  // 879
	Red(1, ast.Item),       // 880
	Red(1, ast.Item),       // 881
	Red(3, ast.Binary),     // 882
	Red(3, ast.Binary),     // 883
	Red(1, ast.Item),       // 884
	Red(1, ast.Item),       // 885
	Err(errors.Errors[6]),  // 886
	Red(1, ast.Item),       // 887
	Err(errors.Errors[6]),  // 888
	Red(1, ast.Item),       // 889
	Red(3, ast.Return),     // 890
	Err(errors.Errors[6]),  // 891
	Err(errors.Errors[6]),  // 892
	Err(errors.Errors[6]),  // 893
	Err(errors.Errors[6]),  // 894
	Red(3, ast.Return),     // 895
	Red(1, ast.Item),       // 896
	Red(3, ast.Return),     // 897
	Red(3, ast.Return),     // 898
	Err(errors.Errors[6]),  // 899
	Red(1, ast.Item),       // 900
	Red(3, ast.Return),     // 901
	Red(3, ast.Return),     // 902
	Err(errors.Errors[6]),  // 903
	Red(3, ast.Return),     // 904
	Err(errors.Errors[6]),  // 905
	Red(3, ast.Return),     // 906
	Err(errors.Errors[6]),  // 907
	Err(errors.Errors[6]),  // 908
	Red(1, ast.Item),       // 909
	Err(errors.Errors[6]),  // 910
	Red(1, ast.Item),       // 911
	Red(1, ast.Item),       // 912
	Red(3, ast.Return),     // 913
	Err(errors.Errors[6]),  // 914
	Err(errors.Errors[6]),  // 915
	Red(1, ast.Item),       // 916
	Red(3, ast.Return),     // 917
	Red(1, ast.Item),       // 918
	Red(1, ast.Item),       // 919
	Err(errors.Errors[6]),  // 920
	Err(errors.Errors[6]),  // 921
	Red(1, ast.Item),       // 922
	Red(1, ast.Item),       // 923
	Err(errors.Errors[6]),  // 924
	Red(1, ast.Item),       // 925
	Red(3, ast.Return),     // 926
	Red(1, ast.Item),       // 927
	Red(2, ast.ExprStmt),   // 928
	Red(3, ast.Return),     // 929
	Err(errors.Errors[6]),  // 930
	Red(1, ast.Item),       // 931
	Red(1, ast.Item),       // 932
	Red(2, ast.ExprStmt),   // 933
	Red(1, ast.Item),       // 934
	Red(2, ast.ExprStmt),   // 935
	Red(2, ast.ExprStmt),   // 936
	Err(errors.Errors[6]),  // 937
	Red(1, ast.Item),       // 938
	Red(2, ast.ExprStmt),   // 939
	Red(2, ast.ExprStmt),   // 940
	Err(errors.Errors[6]),  // 941
	Red(2, ast.ExprStmt),   // 942
	Err(errors.Errors[6]),  // 943
	Red(2, ast.ExprStmt),   // 944
	Err(errors.Errors[6]),  // 945
	Err(errors.Errors[6]),  // 946
	Red(1, ast.Item),       // 947
	Red(3, ast.Return),     // 948
	Red(3, ast.Return),     // 949
	Red(1, ast.Item),       // 950
	Red(2, ast.ExprStmt),   // 951
	Err(errors.Errors[6]),  // 952
	Err(errors.Errors[6]),  // 953
	Sh(11),                 // 954
	Red(2, ast.ExprStmt),   // 955
	Sh(8),                  // 956
	Sh(22),                 // 957
	Err(errors.Errors[6]),  // 958
	Err(errors.Errors[6]),  // 959
	Sh(4),                  // 960
	Sh(27),                 // 961
	Err(errors.Errors[6]),  // 962
	Err(errors.Errors[6]),  // 963
	Red(2, ast.ExprStmt),   // 964
	Err(errors.Errors[6]),  // 965
	Red(0, ast.Items),      // 966
	Red(2, ast.ExprStmt),   // 967
	Err(errors.Errors[6]),  // 968
	Red(1, ast.Item),       // 969
	Red(1, ast.Item),       // 970
	Sh(11),                 // 971
	Err(errors.Errors[6]),  // 972
	Sh(8),                  // 973
	Sh(22),                 // 974
	Err(errors.Errors[6]),  // 975
	Err(errors.Errors[6]),  // 976
	Sh(4),                  // 977
	Sh(9),                  // 978
	Err(errors.Errors[6]),  // 979
	Sh(24),                 // 980
	Err(errors.Errors[6]),  // 981
	Sh(15),                 // 982
	Red(1, ast.Item),       // 983
	Err(errors.Errors[6]),  // 984
	Sh(16),                 // 985
	Red(2, ast.ExprStmt),   // 986
	Red(2, ast.ExprStmt),   // 987
	Red(1, ast.Item),       // 988
	Sh(20),                 // 989
	Red(1, ast.Item),       // 990
	Red(1, ast.Item),       // 991
	Err(errors.Errors[6]),  // 992
	Sh(10),                 // 993
	Red(1, ast.Item),       // 994
	Red(1, ast.Item),       // 995
	Err(errors.Errors[6]),  // 996
	Red(1, ast.Item),       // 997
	Err(errors.Errors[6]),  // 998
	Red(1, ast.Item),       // 999
	Err(errors.Errors[6]),  // 1000
	Err(errors.Errors[6]),  // 1001
	Sh(16),                 // 1002
	Err(errors.Errors[6]),  // 1003
	Red(1, ast.Item),       // 1004
	Red(0, ast.Items),      // 1005
	Red(1, ast.Item),       // 1006
	Sh(23),                 // 1007
	Sh(1),                  // 1008
	Red(1, ast.Item),       // 1009
	Red(1, ast.Item),       // 1010
	Red(1, ast.Item),       // 1011
	Red(1, ast.Item),       // 1012
	Err(errors.Errors[6]),  // 1013
	Err(errors.Errors[6]),  // 1014
	Red(1, ast.Item),       // 1015
	Red(1, ast.Item),       // 1016
	Err(errors.Errors[6]),  // 1017
	Red(1, ast.Item),       // 1018
	Red(1, ast.Item),       // 1019
	Red(1, ast.Item),       // 1020
	Red(5, ast.Let),        // 1021
	Red(1, ast.Item),       // 1022
	Err(errors.Errors[6]),  // 1023
	Sh(23),                 // 1024
	Sh(1),                  // 1025
	Red(5, ast.Let),        // 1026
	Red(1, ast.Item),       // 1027
	Red(5, ast.Let),        // 1028
	Red(5, ast.Let),        // 1029
	Err(errors.Errors[6]),  // 1030
	Red(1, ast.Item),       // 1031
	Red(5, ast.Let),        // 1032
	Red(5, ast.Let),        // 1033
	Err(errors.Errors[6]),  // 1034
	Red(5, ast.Let),        // 1035
	Err(errors.Errors[6]),  // 1036
	Red(5, ast.Let),        // 1037
	Err(errors.Errors[6]),  // 1038
	Err(errors.Errors[6]),  // 1039
	Red(1, ast.Item),       // 1040
	Red(1, ast.Item),       // 1041
	Red(1, ast.Item),       // 1042
	Red(1, ast.Item),       // 1043
	Red(5, ast.Let),        // 1044
	Err(errors.Errors[6]),  // 1045
	Err(errors.Errors[6]),  // 1046
	Sh(11),                 // 1047
	Red(5, ast.Let),        // 1048
	Sh(8),                  // 1049
	Sh(22),                 // 1050
	Err(errors.Errors[6]),  // 1051
	Err(errors.Errors[6]),  // 1052
	Sh(4),                  // 1053
	Sh(27),                 // 1054
	Err(errors.Errors[6]),  // 1055
	Err(errors.Errors[6]),  // 1056
	Red(5, ast.Let),        // 1057
	Err(errors.Errors[6]),  // 1058
	Red(3, ast.Use),        // 1059
	Red(5, ast.Let),        // 1060
	Err(errors.Errors[6]),  // 1061
	Red(1, ast.Item),       // 1062
	Red(1, ast.Item),       // 1063
	Red(3, ast.Use),        // 1064
	Err(errors.Errors[6]),  // 1065
	Red(3, ast.Use),        // 1066
	Red(3, ast.Use),        // 1067
	Err(errors.Errors[6]),  // 1068
	Err(errors.Errors[6]),  // 1069
	Red(3, ast.Use),        // 1070
	Red(3, ast.Use),        // 1071
	Err(errors.Errors[6]),  // 1072
	Red(3, ast.Use),        // 1073
	Err(errors.Errors[6]),  // 1074
	Red(3, ast.Use),        // 1075
	Red(0, ast.Items),      // 1076
	Err(errors.Errors[6]),  // 1077
	Sh(16),                 // 1078
	Red(5, ast.Let),        // 1079
	Red(5, ast.Let),        // 1080
	Sh(11),                 // 1081
	Red(3, ast.Use),        // 1082
	Sh(8),                  // 1083
	Sh(22),                 // 1084
	Err(errors.Errors[6]),  // 1085
	Red(3, ast.Use),        // 1086
	Sh(4),                  // 1087
	Sh(9),                  // 1088
	Err(errors.Errors[6]),  // 1089
	Sh(24),                 // 1090
	Err(errors.Errors[6]),  // 1091
	Sh(15),                 // 1092
	Err(errors.Errors[6]),  // 1093
	Err(errors.Errors[6]),  // 1094
	Red(3, ast.Use),        // 1095
	Err(errors.Errors[6]),  // 1096
	Red(0, ast.Items),      // 1097
	Red(3, ast.Use),        // 1098
	Sh(20),                 // 1099
	Sh(23),                 // 1100
	Sh(1),                  // 1101
	Sh(11),                 // 1102
	Sh(10),                 // 1103
	Sh(8),                  // 1104
	Sh(22),                 // 1105
	Err(errors.Errors[6]),  // 1106
	Err(errors.Errors[6]),  // 1107
	Sh(4),                  // 1108
	Sh(9),                  // 1109
	Err(errors.Errors[6]),  // 1110
	Sh(24),                 // 1111
	Sh(16),                 // 1112
	Sh(15),                 // 1113
	Red(1, ast.Item),       // 1114
	Red(0, ast.Items),      // 1115
	Err(errors.Errors[6]),  // 1116
	Red(3, ast.Use),        // 1117
	Red(3, ast.Use),        // 1118
	Red(1, ast.Item),       // 1119
	Sh(20),                 // 1120
	Red(1, ast.Item),       // 1121
	Red(1, ast.Item),       // 1122
	Err(errors.Errors[6]),  // 1123
	Sh(10),                 // 1124
	Red(1, ast.Item),       // 1125
	Red(1, ast.Item),       // 1126
	Err(errors.Errors[6]),  // 1127
	Red(1, ast.Item),       // 1128
	Err(errors.Errors[6]),  // 1129
	Red(1, ast.Item),       // 1130
	Err(errors.Errors[6]),  // 1131
	Err(errors.Errors[6]),  // 1132
	Sh(16),                 // 1133
	Sh(23),                 // 1134
	Sh(1),                  // 1135
	Red(0, ast.Items),      // 1136
	Red(1, ast.Item),       // 1137
	Err(errors.Errors[6]),  // 1138
	Err(errors.Errors[6]),  // 1139
	Sh(11),                 // 1140
	Red(1, ast.Item),       // 1141
	Sh(8),                  // 1142
	Sh(22),                 // 1143
	Err(errors.Errors[6]),  // 1144
	Err(errors.Errors[6]),  // 1145
	Sh(4),                  // 1146
	Sh(9),                  // 1147
	Err(errors.Errors[6]),  // 1148
	Err(errors.Errors[6]),  // 1149
	Red(1, ast.Item),       // 1150
	Err(errors.Errors[6]),  // 1151
	Red(5, ast.If),         // 1152
	Red(1, ast.Item),       // 1153
	Err(errors.Errors[6]),  // 1154
	Sh(23),                 // 1155
	Sh(1),                  // 1156
	Red(5, ast.If),         // 1157
	Err(errors.Errors[6]),  // 1158
	Red(5, ast.If),         // 1159
	Red(5, ast.If),         // 1160
	Err(errors.Errors[6]),  // 1161
	Err(errors.Errors[6]),  // 1162
	Red(5, ast.If),         // 1163
	Red(5, ast.If),         // 1164
	Err(errors.Errors[6]),  // 1165
	Red(5, ast.If),         // 1166
	Err(errors.Errors[6]),  // 1167
	Red(5, ast.If),         // 1168
	Err(errors.Errors[6]),  // 1169
	Err(errors.Errors[6]),  // 1170
	Sh(16),                 // 1171
	Red(1, ast.Item),       // 1172
	Red(1, ast.Item),       // 1173
	Sh(11),                 // 1174
	Red(5, ast.If),         // 1175
	Sh(8),                  // 1176
	Sh(22),                 // 1177
	Err(errors.Errors[6]),  // 1178
	Red(5, ast.If),         // 1179
	Sh(4),                  // 1180
	Sh(9),                  // 1181
	Err(errors.Errors[6]),  // 1182
	Sh(11),                 // 1183
	Err(errors.Errors[6]),  // 1184
	Sh(8),                  // 1185
	Sh(22),                 // 1186
	Err(errors.Errors[6]),  // 1187
	Red(5, ast.If),         // 1188
	Sh(4),                  // 1189
	Sh(9),                  // 1190
	Red(5, ast.If),         // 1191
	Err(errors.Errors[6]),  // 1192
	Sh(23),                 // 1193
	Sh(1),                  // 1194
	Sh(11),                 // 1195
	Err(errors.Errors[6]),  // 1196
	Sh(8),                  // 1197
	Sh(22),                 // 1198
	Err(errors.Errors[6]),  // 1199
	Err(errors.Errors[6]),  // 1200
	Sh(4),                  // 1201
	Sh(9),                  // 1202
	Err(errors.Errors[6]),  // 1203
	Err(errors.Errors[6]),  // 1204
	Sh(16),                 // 1205
	Err(errors.Errors[6]),  // 1206
	Err(errors.Errors[6]),  // 1207
	Err(errors.Errors[6]),  // 1208
	Err(errors.Errors[6]),  // 1209
	Red(5, ast.If),         // 1210
	Red(5, ast.If),         // 1211
	Err(errors.Errors[6]),  // 1212
	Sh(11),                 // 1213
	Sh(16),                 // 1214
	Sh(8),                  // 1215
	Sh(22),                 // 1216
	Err(errors.Errors[6]),  // 1217
	Err(errors.Errors[6]),  // 1218
	Sh(4),                  // 1219
	Sh(27),                 // 1220
	Err(errors.Errors[6]),  // 1221
	Err(errors.Errors[6]),  // 1222
	Err(errors.Errors[6]),  // 1223
	Err(errors.Errors[6]),  // 1224
	Err(errors.Errors[6]),  // 1225
	Sh(16),                 // 1226
	Sh(23),                 // 1227
	Sh(1),                  // 1228
	Err(errors.Errors[6]),  // 1229
	Err(errors.Errors[6]),  // 1230
	Err(errors.Errors[6]),  // 1231
	Sh(11),                 // 1232
	Err(errors.Errors[6]),  // 1233
	Sh(8),                  // 1234
	Sh(22),                 // 1235
	Sh(23),                 // 1236
	Sh(1),                  // 1237
	Sh(4),                  // 1238
	Sh(27),                 // 1239
	Sh(11),                 // 1240
	Err(errors.Errors[6]),  // 1241
	Sh(8),                  // 1242
	Sh(22),                 // 1243
	Sh(16),                 // 1244
	Err(errors.Errors[6]),  // 1245
	Sh(4),                  // 1246
	Sh(9),                  // 1247
	Sh(23),                 // 1248
	Sh(1),                  // 1249
	Sh(11),                 // 1250
	Err(errors.Errors[6]),  // 1251
	Sh(8),                  // 1252
	Sh(22),                 // 1253
	Err(errors.Errors[6]),  // 1254
	Err(errors.Errors[6]),  // 1255
	Sh(4),                  // 1256
	Sh(27),                 // 1257
	Sh(11),                 // 1258
	Err(errors.Errors[6]),  // 1259
	Sh(8),                  // 1260
	Sh(22),                 // 1261
	Err(errors.Errors[6]),  // 1262
	Sh(16),                 // 1263
	Sh(4),                  // 1264
	Sh(27),                 // 1265
	Sh(23),                 // 1266
	Sh(1),                  // 1267
	Err(errors.Errors[6]),  // 1268
	Err(errors.Errors[6]),  // 1269
	Sh(11),                 // 1270
	Sh(16),                 // 1271
	Sh(8),                  // 1272
	Sh(22),                 // 1273
	Err(errors.Errors[6]),  // 1274
	Err(errors.Errors[6]),  // 1275
	Sh(4),                  // 1276
	Sh(27),                 // 1277
	Err(errors.Errors[6]),  // 1278
	Err(errors.Errors[6]),  // 1279
	Err(errors.Errors[6]),  // 1280
	Sh(16),                 // 1281
	Err(errors.Errors[6]),  // 1282
	Err(errors.Errors[6]),  // 1283
	Err(errors.Errors[6]),  // 1284
	Sh(23),                 // 1285
	Sh(1),                  // 1286
	Err(errors.Errors[6]),  // 1287
	Err(errors.Errors[6]),  // 1288
	Sh(16),                 // 1289
	Err(errors.Errors[6]),  // 1290
	Err(errors.Errors[6]),  // 1291
	Err(errors.Errors[6]),  // 1292
	Sh(23),                 // 1293
	Sh(1),                  // 1294
	Err(errors.Errors[6]),  // 1295
	Err(errors.Errors[6]),  // 1296
	Err(errors.Errors[6]),  // 1297
	Err(errors.Errors[6]),  // 1298
	Err(errors.Errors[6]),  // 1299
	Err(errors.Errors[6]),  // 1300
	Sh(16),                 // 1301
	Err(errors.Errors[6]),  // 1302
	Sh(23),                 // 1303
	Sh(1),                  // 1304
	Err(errors.Errors[6]),  // 1305
	Err(errors.Errors[6]),  // 1306
	Sh(11),                 // 1307
	Err(errors.Errors[6]),  // 1308
	Sh(8),                  // 1309
	Sh(22),                 // 1310
	Sh(23),                 // 1311
	Sh(1),                  // 1312
	Sh(4),                  // 1313
	Sh(27),                 // 1314
	Sh(11),                 // 1315
	Err(errors.Errors[6]),  // 1316
	Sh(8),                  // 1317
	Sh(22),                 // 1318
	Err(errors.Errors[6]),  // 1319
	Err(errors.Errors[6]),  // 1320
	Sh(4),                  // 1321
	Sh(27),                 // 1322
	Sh(23),                 // 1323
	Sh(1),                  // 1324
	Sh(11),                 // 1325
	Err(errors.Errors[6]),  // 1326
	Sh(8),                  // 1327
	Sh(22),                 // 1328
	Err(errors.Errors[6]),  // 1329
	Err(errors.Errors[6]),  // 1330
	Sh(4),                  // 1331
	Sh(27),                 // 1332
	Sh(11),                 // 1333
	Err(errors.Errors[6]),  // 1334
	Sh(8),                  // 1335
	Sh(22),                 // 1336
	Err(errors.Errors[6]),  // 1337
	Sh(16),                 // 1338
	Sh(4),                  // 1339
	Sh(27),                 // 1340
	Sh(11),                 // 1341
	Err(errors.Errors[6]),  // 1342
	Sh(8),                  // 1343
	Sh(22),                 // 1344
	Err(errors.Errors[6]),  // 1345
	Sh(16),                 // 1346
	Sh(4),                  // 1347
	Sh(27),                 // 1348
	Err(errors.Errors[6]),  // 1349
	Err(errors.Errors[6]),  // 1350
	Sh(11),                 // 1351
	Err(errors.Errors[6]),  // 1352
	Sh(8),                  // 1353
	Sh(22),                 // 1354
	Err(errors.Errors[6]),  // 1355
	Sh(16),                 // 1356
	Sh(4),                  // 1357
	Sh(27),                 // 1358
	Err(errors.Errors[6]),  // 1359
	Sh(23),                 // 1360
	Sh(1),                  // 1361
	Err(errors.Errors[6]),  // 1362
	Err(errors.Errors[6]),  // 1363
	Sh(16),                 // 1364
	Err(errors.Errors[6]),  // 1365
	Err(errors.Errors[6]),  // 1366
	Err(errors.Errors[6]),  // 1367
	Sh(23),                 // 1368
	Sh(1),                  // 1369
	Err(errors.Errors[6]),  // 1370
	Err(errors.Errors[6]),  // 1371
	Sh(16),                 // 1372
	Err(errors.Errors[6]),  // 1373
	Err(errors.Errors[6]),  // 1374
	Err(errors.Errors[6]),  // 1375
	Err(errors.Errors[6]),  // 1376
	Err(errors.Errors[6]),  // 1377
	Sh(23),                 // 1378
	Sh(1),                  // 1379
	Err(errors.Errors[6]),  // 1380
	Err(errors.Errors[6]),  // 1381
	Sh(16),                 // 1382
	Err(errors.Errors[6]),  // 1383
	Err(errors.Errors[6]),  // 1384
	Err(errors.Errors[6]),  // 1385
	Sh(23),                 // 1386
	Sh(1),                  // 1387
	Err(errors.Errors[6]),  // 1388
	Err(errors.Errors[6]),  // 1389
	Err(errors.Errors[6]),  // 1390
	Err(errors.Errors[6]),  // 1391
	Err(errors.Errors[6]),  // 1392
	Err(errors.Errors[6]),  // 1393
	Sh(23),                 // 1394
	Sh(1),                  // 1395
	Err(errors.Errors[6]),  // 1396
	Err(errors.Errors[6]),  // 1397
	Err(errors.Errors[6]),  // 1398
	Err(errors.Errors[6]),  // 1399
	Err(errors.Errors[6]),  // 1400
	Err(errors.Errors[6]),  // 1401
	Err(errors.Errors[6]),  // 1402
	Err(errors.Errors[6]),  // 1403
	Sh(23),                 // 1404
	Sh(1),                  // 1405
}

var Check = []int{
	-1, // 0
	-1, // 1
	-1, // 2
	-1, // 3
	-1, // 4
	44, // 5
	45, // 6
	14, // 7
	19, // 8
	-1, // 9
	79, // 10
	-1, // 11
	-1, // 12
	-1, // 13
	-1, // 14
	79, // 15
	-1, // 16
	79, // 17
	79, // 18
	15, // 19
	24, // 20
	79, // 21
	79, // 22
	-1, // 23
	79, // 24
	-1, // 25
	79, // 26
	-1, // 27
	-1, // 28
	42, // 29
	-1, // 30
	42, // 31
	42, // 32
	79, // 33
	-1, // 34
	42, // 35
	42, // 36
	79, // 37
	79, // 38
	-1, // 39
	-1, // 40
	9,  // 41
	9,  // 42
	9,  // 43
	44, // 44
	74, // 45
	79, // 46
	9,  // 47
	47, // 48
	79, // 49
	62, // 50
	62, // 51
	46, // 52
	72, // 53
	9,  // 54
	9,  // 55
	9,  // 56
	9,  // 57
	9,  // 58
	9,  // 59
	42, // 60
	42, // 61
	77, // 62
	9,  // 63
	9,  // 64
	9,  // 65
	9,  // 66
	9,  // 67
	79, // 68
	79, // 69
	2,  // 70
	2,  // 71
	64, // 72
	27, // 73
	27, // 74
	27, // 75
	75, // 76
	63, // 77
	43, // 78
	81, // 79
	-1, // 80
	-1, // 81
	42, // 82
	42, // 83
	9,  // 84
	9,  // 85
	27, // 86
	27, // 87
	27, // 88
	27, // 89
	27, // 90
	27, // 91
	62, // 92
	62, // 93
	48, // 94
	27, // 95
	27, // 96
	27, // 97
	27, // 98
	27, // 99
	76, // 100
	6,  // 101
	50, // 102
	-1, // 103
	-1, // 104
	77, // 105
	59, // 106
	59, // 107
	-1, // 108
	-1, // 109
	-1, // 110
	-1, // 111
	2,  // 112
	2,  // 113
	-1, // 114
	64, // 115
	27, // 116
	27, // 117
	59, // 118
	59, // 119
	59, // 120
	59, // 121
	59, // 122
	59, // 123
	-1, // 124
	-1, // 125
	-1, // 126
	59, // 127
	59, // 128
	59, // 129
	59, // 130
	59, // 131
	-1, // 132
	-1, // 133
	-1, // 134
	-1, // 135
	-1, // 136
	-1, // 137
	55, // 138
	55, // 139
	-1, // 140
	-1, // 141
	-1, // 142
	-1, // 143
	-1, // 144
	-1, // 145
	-1, // 146
	-1, // 147
	59, // 148
	59, // 149
	55, // 150
	55, // 151
	55, // 152
	55, // 153
	55, // 154
	55, // 155
	-1, // 156
	-1, // 157
	-1, // 158
	55, // 159
	55, // 160
	55, // 161
	55, // 162
	55, // 163
	-1, // 164
	-1, // 165
	-1, // 166
	-1, // 167
	-1, // 168
	-1, // 169
	4,  // 170
	4,  // 171
	-1, // 172
	-1, // 173
	-1, // 174
	-1, // 175
	-1, // 176
	-1, // 177
	-1, // 178
	-1, // 179
	55, // 180
	55, // 181
	4,  // 182
	4,  // 183
	4,  // 184
	4,  // 185
	4,  // 186
	4,  // 187
	-1, // 188
	-1, // 189
	-1, // 190
	4,  // 191
	4,  // 192
	4,  // 193
	4,  // 194
	4,  // 195
	-1, // 196
	-1, // 197
	-1, // 198
	-1, // 199
	-1, // 200
	-1, // 201
	5,  // 202
	5,  // 203
	-1, // 204
	-1, // 205
	-1, // 206
	-1, // 207
	-1, // 208
	-1, // 209
	-1, // 210
	-1, // 211
	4,  // 212
	4,  // 213
	5,  // 214
	5,  // 215
	5,  // 216
	5,  // 217
	5,  // 218
	5,  // 219
	-1, // 220
	-1, // 221
	-1, // 222
	5,  // 223
	5,  // 224
	5,  // 225
	5,  // 226
	5,  // 227
	-1, // 228
	-1, // 229
	-1, // 230
	-1, // 231
	-1, // 232
	-1, // 233
	49, // 234
	49, // 235
	-1, // 236
	-1, // 237
	-1, // 238
	-1, // 239
	-1, // 240
	-1, // 241
	-1, // 242
	-1, // 243
	5,  // 244
	5,  // 245
	49, // 246
	49, // 247
	49, // 248
	49, // 249
	49, // 250
	49, // 251
	-1, // 252
	-1, // 253
	-1, // 254
	49, // 255
	49, // 256
	49, // 257
	49, // 258
	49, // 259
	-1, // 260
	-1, // 261
	-1, // 262
	-1, // 263
	-1, // 264
	-1, // 265
	51, // 266
	51, // 267
	-1, // 268
	-1, // 269
	-1, // 270
	-1, // 271
	-1, // 272
	-1, // 273
	-1, // 274
	-1, // 275
	49, // 276
	49, // 277
	51, // 278
	51, // 279
	51, // 280
	51, // 281
	51, // 282
	51, // 283
	-1, // 284
	-1, // 285
	-1, // 286
	51, // 287
	51, // 288
	51, // 289
	51, // 290
	51, // 291
	-1, // 292
	-1, // 293
	-1, // 294
	-1, // 295
	-1, // 296
	-1, // 297
	8,  // 298
	8,  // 299
	-1, // 300
	-1, // 301
	-1, // 302
	-1, // 303
	-1, // 304
	-1, // 305
	-1, // 306
	-1, // 307
	51, // 308
	51, // 309
	8,  // 310
	8,  // 311
	8,  // 312
	8,  // 313
	8,  // 314
	8,  // 315
	-1, // 316
	-1, // 317
	-1, // 318
	8,  // 319
	8,  // 320
	8,  // 321
	8,  // 322
	8,  // 323
	-1, // 324
	-1, // 325
	-1, // 326
	-1, // 327
	-1, // 328
	-1, // 329
	71, // 330
	71, // 331
	-1, // 332
	-1, // 333
	-1, // 334
	-1, // 335
	-1, // 336
	-1, // 337
	-1, // 338
	-1, // 339
	8,  // 340
	8,  // 341
	71, // 342
	71, // 343
	71, // 344
	71, // 345
	71, // 346
	71, // 347
	-1, // 348
	-1, // 349
	-1, // 350
	71, // 351
	71, // 352
	71, // 353
	71, // 354
	71, // 355
	-1, // 356
	-1, // 357
	-1, // 358
	-1, // 359
	-1, // 360
	-1, // 361
	11, // 362
	11, // 363
	-1, // 364
	-1, // 365
	-1, // 366
	-1, // 367
	-1, // 368
	-1, // 369
	-1, // 370
	-1, // 371
	71, // 372
	71, // 373
	11, // 374
	11, // 375
	11, // 376
	11, // 377
	11, // 378
	11, // 379
	-1, // 380
	-1, // 381
	-1, // 382
	11, // 383
	11, // 384
	11, // 385
	11, // 386
	11, // 387
	-1, // 388
	-1, // 389
	-1, // 390
	-1, // 391
	-1, // 392
	-1, // 393
	52, // 394
	52, // 395
	-1, // 396
	-1, // 397
	-1, // 398
	-1, // 399
	-1, // 400
	-1, // 401
	-1, // 402
	-1, // 403
	11, // 404
	11, // 405
	52, // 406
	52, // 407
	52, // 408
	52, // 409
	52, // 410
	52, // 411
	-1, // 412
	-1, // 413
	-1, // 414
	52, // 415
	52, // 416
	52, // 417
	52, // 418
	52, // 419
	-1, // 420
	-1, // 421
	-1, // 422
	-1, // 423
	-1, // 424
	-1, // 425
	53, // 426
	53, // 427
	-1, // 428
	-1, // 429
	-1, // 430
	-1, // 431
	-1, // 432
	-1, // 433
	-1, // 434
	-1, // 435
	52, // 436
	52, // 437
	53, // 438
	53, // 439
	53, // 440
	53, // 441
	53, // 442
	53, // 443
	-1, // 444
	-1, // 445
	-1, // 446
	53, // 447
	53, // 448
	53, // 449
	53, // 450
	53, // 451
	-1, // 452
	-1, // 453
	-1, // 454
	-1, // 455
	-1, // 456
	-1, // 457
	54, // 458
	54, // 459
	-1, // 460
	-1, // 461
	-1, // 462
	-1, // 463
	-1, // 464
	-1, // 465
	-1, // 466
	-1, // 467
	53, // 468
	53, // 469
	54, // 470
	54, // 471
	54, // 472
	54, // 473
	54, // 474
	54, // 475
	-1, // 476
	-1, // 477
	-1, // 478
	54, // 479
	54, // 480
	54, // 481
	54, // 482
	54, // 483
	-1, // 484
	-1, // 485
	-1, // 486
	-1, // 487
	-1, // 488
	-1, // 489
	28, // 490
	28, // 491
	-1, // 492
	-1, // 493
	-1, // 494
	-1, // 495
	-1, // 496
	-1, // 497
	-1, // 498
	-1, // 499
	54, // 500
	54, // 501
	28, // 502
	28, // 503
	28, // 504
	28, // 505
	28, // 506
	28, // 507
	-1, // 508
	-1, // 509
	-1, // 510
	28, // 511
	28, // 512
	28, // 513
	28, // 514
	28, // 515
	-1, // 516
	-1, // 517
	-1, // 518
	-1, // 519
	-1, // 520
	-1, // 521
	68, // 522
	68, // 523
	-1, // 524
	-1, // 525
	-1, // 526
	-1, // 527
	-1, // 528
	-1, // 529
	-1, // 530
	-1, // 531
	28, // 532
	28, // 533
	68, // 534
	68, // 535
	68, // 536
	68, // 537
	68, // 538
	68, // 539
	-1, // 540
	-1, // 541
	-1, // 542
	68, // 543
	68, // 544
	68, // 545
	68, // 546
	68, // 547
	-1, // 548
	-1, // 549
	-1, // 550
	-1, // 551
	-1, // 552
	-1, // 553
	56, // 554
	56, // 555
	-1, // 556
	-1, // 557
	-1, // 558
	-1, // 559
	-1, // 560
	-1, // 561
	-1, // 562
	-1, // 563
	68, // 564
	68, // 565
	56, // 566
	56, // 567
	56, // 568
	56, // 569
	56, // 570
	56, // 571
	-1, // 572
	-1, // 573
	-1, // 574
	56, // 575
	56, // 576
	56, // 577
	56, // 578
	56, // 579
	-1, // 580
	-1, // 581
	-1, // 582
	-1, // 583
	-1, // 584
	-1, // 585
	57, // 586
	57, // 587
	-1, // 588
	-1, // 589
	-1, // 590
	-1, // 591
	-1, // 592
	-1, // 593
	-1, // 594
	-1, // 595
	56, // 596
	56, // 597
	57, // 598
	57, // 599
	57, // 600
	57, // 601
	57, // 602
	57, // 603
	-1, // 604
	-1, // 605
	-1, // 606
	57, // 607
	57, // 608
	57, // 609
	57, // 610
	57, // 611
	-1, // 612
	-1, // 613
	-1, // 614
	-1, // 615
	-1, // 616
	-1, // 617
	58, // 618
	58, // 619
	-1, // 620
	-1, // 621
	-1, // 622
	-1, // 623
	-1, // 624
	-1, // 625
	-1, // 626
	-1, // 627
	57, // 628
	57, // 629
	58, // 630
	58, // 631
	58, // 632
	58, // 633
	58, // 634
	58, // 635
	-1, // 636
	-1, // 637
	-1, // 638
	58, // 639
	58, // 640
	58, // 641
	58, // 642
	58, // 643
	-1, // 644
	-1, // 645
	-1, // 646
	-1, // 647
	-1, // 648
	-1, // 649
	3,  // 650
	3,  // 651
	-1, // 652
	-1, // 653
	-1, // 654
	-1, // 655
	-1, // 656
	-1, // 657
	-1, // 658
	-1, // 659
	58, // 660
	58, // 661
	3,  // 662
	3,  // 663
	3,  // 664
	3,  // 665
	3,  // 666
	3,  // 667
	-1, // 668
	-1, // 669
	-1, // 670
	3,  // 671
	3,  // 672
	3,  // 673
	3,  // 674
	3,  // 675
	-1, // 676
	-1, // 677
	-1, // 678
	-1, // 679
	-1, // 680
	-1, // 681
	18, // 682
	18, // 683
	-1, // 684
	-1, // 685
	-1, // 686
	-1, // 687
	-1, // 688
	-1, // 689
	-1, // 690
	-1, // 691
	3,  // 692
	3,  // 693
	18, // 694
	18, // 695
	18, // 696
	18, // 697
	18, // 698
	18, // 699
	-1, // 700
	-1, // 701
	-1, // 702
	18, // 703
	18, // 704
	18, // 705
	18, // 706
	18, // 707
	-1, // 708
	-1, // 709
	-1, // 710
	-1, // 711
	-1, // 712
	-1, // 713
	25, // 714
	25, // 715
	-1, // 716
	-1, // 717
	-1, // 718
	-1, // 719
	-1, // 720
	-1, // 721
	-1, // 722
	-1, // 723
	18, // 724
	18, // 725
	25, // 726
	25, // 727
	25, // 728
	25, // 729
	25, // 730
	25, // 731
	-1, // 732
	-1, // 733
	-1, // 734
	25, // 735
	25, // 736
	25, // 737
	25, // 738
	25, // 739
	-1, // 740
	-1, // 741
	20, // 742
	-1, // 743
	20, // 744
	20, // 745
	-1, // 746
	65, // 747
	20, // 748
	20, // 749
	-1, // 750
	-1, // 751
	65, // 752
	-1, // 753
	65, // 754
	65, // 755
	25, // 756
	25, // 757
	65, // 758
	65, // 759
	-1, // 760
	65, // 761
	-1, // 762
	65, // 763
	-1, // 764
	-1, // 765
	-1, // 766
	-1, // 767
	-1, // 768
	-1, // 769
	65, // 770
	-1, // 771
	-1, // 772
	20, // 773
	65, // 774
	65, // 775
	61, // 776
	61, // 777
	-1, // 778
	-1, // 779
	-1, // 780
	-1, // 781
	-1, // 782
	65, // 783
	-1, // 784
	-1, // 785
	65, // 786
	-1, // 787
	61, // 788
	61, // 789
	61, // 790
	61, // 791
	61, // 792
	61, // 793
	-1, // 794
	20, // 795
	20, // 796
	61, // 797
	61, // 798
	61, // 799
	61, // 800
	61, // 801
	-1, // 802
	-1, // 803
	-1, // 804
	65, // 805
	65, // 806
	-1, // 807
	22, // 808
	22, // 809
	-1, // 810
	-1, // 811
	-1, // 812
	-1, // 813
	-1, // 814
	-1, // 815
	-1, // 816
	-1, // 817
	61, // 818
	61, // 819
	22, // 820
	22, // 821
	22, // 822
	22, // 823
	22, // 824
	22, // 825
	-1, // 826
	-1, // 827
	-1, // 828
	22, // 829
	22, // 830
	22, // 831
	22, // 832
	22, // 833
	-1, // 834
	-1, // 835
	-1, // 836
	-1, // 837
	-1, // 838
	-1, // 839
	60, // 840
	60, // 841
	-1, // 842
	-1, // 843
	-1, // 844
	-1, // 845
	-1, // 846
	-1, // 847
	-1, // 848
	-1, // 849
	22, // 850
	22, // 851
	60, // 852
	60, // 853
	60, // 854
	60, // 855
	60, // 856
	60, // 857
	-1, // 858
	-1, // 859
	-1, // 860
	60, // 861
	60, // 862
	60, // 863
	60, // 864
	60, // 865
	-1, // 866
	-1, // 867
	-1, // 868
	-1, // 869
	-1, // 870
	-1, // 871
	-1, // 872
	12, // 873
	-1, // 874
	-1, // 875
	-1, // 876
	-1, // 877
	12, // 878
	-1, // 879
	12, // 880
	12, // 881
	60, // 882
	60, // 883
	12, // 884
	12, // 885
	-1, // 886
	12, // 887
	-1, // 888
	12, // 889
	69, // 890
	-1, // 891
	-1, // 892
	-1, // 893
	-1, // 894
	69, // 895
	12, // 896
	69, // 897
	69, // 898
	-1, // 899
	12, // 900
	69, // 901
	69, // 902
	-1, // 903
	69, // 904
	-1, // 905
	69, // 906
	-1, // 907
	-1, // 908
	12, // 909
	-1, // 910
	26, // 911
	12, // 912
	69, // 913
	-1, // 914
	-1, // 915
	26, // 916
	69, // 917
	26, // 918
	26, // 919
	-1, // 920
	-1, // 921
	26, // 922
	26, // 923
	-1, // 924
	26, // 925
	69, // 926
	26, // 927
	40, // 928
	69, // 929
	-1, // 930
	12, // 931
	12, // 932
	40, // 933
	26, // 934
	40, // 935
	40, // 936
	-1, // 937
	26, // 938
	40, // 939
	40, // 940
	-1, // 941
	40, // 942
	-1, // 943
	40, // 944
	-1, // 945
	-1, // 946
	26, // 947
	69, // 948
	69, // 949
	26, // 950
	40, // 951
	-1, // 952
	-1, // 953
	29, // 954
	40, // 955
	29, // 956
	29, // 957
	-1, // 958
	-1, // 959
	29, // 960
	29, // 961
	-1, // 962
	-1, // 963
	40, // 964
	-1, // 965
	66, // 966
	40, // 967
	-1, // 968
	26, // 969
	26, // 970
	66, // 971
	-1, // 972
	66, // 973
	66, // 974
	-1, // 975
	-1, // 976
	66, // 977
	66, // 978
	-1, // 979
	66, // 980
	-1, // 981
	66, // 982
	21, // 983
	-1, // 984
	29, // 985
	40, // 986
	40, // 987
	21, // 988
	66, // 989
	21, // 990
	21, // 991
	-1, // 992
	66, // 993
	21, // 994
	21, // 995
	-1, // 996
	21, // 997
	-1, // 998
	21, // 999
	-1, // 1000
	-1, // 1001
	66, // 1002
	-1, // 1003
	17, // 1004
	66, // 1005
	21, // 1006
	29, // 1007
	29, // 1008
	17, // 1009
	21, // 1010
	17, // 1011
	17, // 1012
	-1, // 1013
	-1, // 1014
	17, // 1015
	17, // 1016
	-1, // 1017
	17, // 1018
	21, // 1019
	17, // 1020
	80, // 1021
	21, // 1022
	-1, // 1023
	66, // 1024
	66, // 1025
	80, // 1026
	17, // 1027
	80, // 1028
	80, // 1029
	-1, // 1030
	17, // 1031
	80, // 1032
	80, // 1033
	-1, // 1034
	80, // 1035
	-1, // 1036
	80, // 1037
	-1, // 1038
	-1, // 1039
	17, // 1040
	21, // 1041
	21, // 1042
	17, // 1043
	80, // 1044
	-1, // 1045
	-1, // 1046
	1,  // 1047
	80, // 1048
	1,  // 1049
	1,  // 1050
	-1, // 1051
	-1, // 1052
	1,  // 1053
	1,  // 1054
	-1, // 1055
	-1, // 1056
	80, // 1057
	-1, // 1058
	70, // 1059
	80, // 1060
	-1, // 1061
	17, // 1062
	17, // 1063
	70, // 1064
	-1, // 1065
	70, // 1066
	70, // 1067
	-1, // 1068
	-1, // 1069
	70, // 1070
	70, // 1071
	-1, // 1072
	70, // 1073
	-1, // 1074
	70, // 1075
	13, // 1076
	-1, // 1077
	1,  // 1078
	80, // 1079
	80, // 1080
	13, // 1081
	70, // 1082
	13, // 1083
	13, // 1084
	-1, // 1085
	70, // 1086
	13, // 1087
	13, // 1088
	-1, // 1089
	13, // 1090
	-1, // 1091
	13, // 1092
	-1, // 1093
	-1, // 1094
	70, // 1095
	-1, // 1096
	0,  // 1097
	70, // 1098
	13, // 1099
	1,  // 1100
	1,  // 1101
	0,  // 1102
	13, // 1103
	0,  // 1104
	0,  // 1105
	-1, // 1106
	-1, // 1107
	0,  // 1108
	0,  // 1109
	-1, // 1110
	0,  // 1111
	13, // 1112
	0,  // 1113
	7,  // 1114
	13, // 1115
	-1, // 1116
	70, // 1117
	70, // 1118
	7,  // 1119
	0,  // 1120
	7,  // 1121
	7,  // 1122
	-1, // 1123
	0,  // 1124
	7,  // 1125
	7,  // 1126
	-1, // 1127
	7,  // 1128
	-1, // 1129
	7,  // 1130
	-1, // 1131
	-1, // 1132
	0,  // 1133
	13, // 1134
	13, // 1135
	0,  // 1136
	7,  // 1137
	-1, // 1138
	-1, // 1139
	73, // 1140
	7,  // 1141
	73, // 1142
	73, // 1143
	-1, // 1144
	-1, // 1145
	73, // 1146
	73, // 1147
	-1, // 1148
	-1, // 1149
	7,  // 1150
	-1, // 1151
	78, // 1152
	7,  // 1153
	-1, // 1154
	0,  // 1155
	0,  // 1156
	78, // 1157
	-1, // 1158
	78, // 1159
	78, // 1160
	-1, // 1161
	-1, // 1162
	78, // 1163
	78, // 1164
	-1, // 1165
	78, // 1166
	-1, // 1167
	78, // 1168
	-1, // 1169
	-1, // 1170
	73, // 1171
	7,  // 1172
	7,  // 1173
	10, // 1174
	78, // 1175
	10, // 1176
	10, // 1177
	-1, // 1178
	78, // 1179
	10, // 1180
	10, // 1181
	-1, // 1182
	16, // 1183
	-1, // 1184
	16, // 1185
	16, // 1186
	-1, // 1187
	78, // 1188
	16, // 1189
	16, // 1190
	78, // 1191
	-1, // 1192
	73, // 1193
	73, // 1194
	67, // 1195
	-1, // 1196
	67, // 1197
	67, // 1198
	-1, // 1199
	-1, // 1200
	67, // 1201
	67, // 1202
	-1, // 1203
	-1, // 1204
	10, // 1205
	-1, // 1206
	-1, // 1207
	-1, // 1208
	-1, // 1209
	78, // 1210
	78, // 1211
	-1, // 1212
	23, // 1213
	16, // 1214
	23, // 1215
	23, // 1216
	-1, // 1217
	-1, // 1218
	23, // 1219
	23, // 1220
	-1, // 1221
	-1, // 1222
	-1, // 1223
	-1, // 1224
	-1, // 1225
	67, // 1226
	10, // 1227
	10, // 1228
	-1, // 1229
	-1, // 1230
	-1, // 1231
	39, // 1232
	-1, // 1233
	39, // 1234
	39, // 1235
	16, // 1236
	16, // 1237
	39, // 1238
	39, // 1239
	41, // 1240
	-1, // 1241
	41, // 1242
	41, // 1243
	23, // 1244
	-1, // 1245
	41, // 1246
	41, // 1247
	67, // 1248
	67, // 1249
	38, // 1250
	-1, // 1251
	38, // 1252
	38, // 1253
	-1, // 1254
	-1, // 1255
	38, // 1256
	38, // 1257
	37, // 1258
	-1, // 1259
	37, // 1260
	37, // 1261
	-1, // 1262
	39, // 1263
	37, // 1264
	37, // 1265
	23, // 1266
	23, // 1267
	-1, // 1268
	-1, // 1269
	36, // 1270
	41, // 1271
	36, // 1272
	36, // 1273
	-1, // 1274
	-1, // 1275
	36, // 1276
	36, // 1277
	-1, // 1278
	-1, // 1279
	-1, // 1280
	38, // 1281
	-1, // 1282
	-1, // 1283
	-1, // 1284
	39, // 1285
	39, // 1286
	-1, // 1287
	-1, // 1288
	37, // 1289
	-1, // 1290
	-1, // 1291
	-1, // 1292
	41, // 1293
	41, // 1294
	-1, // 1295
	-1, // 1296
	-1, // 1297
	-1, // 1298
	-1, // 1299
	-1, // 1300
	36, // 1301
	-1, // 1302
	38, // 1303
	38, // 1304
	-1, // 1305
	-1, // 1306
	35, // 1307
	-1, // 1308
	35, // 1309
	35, // 1310
	37, // 1311
	37, // 1312
	35, // 1313
	35, // 1314
	34, // 1315
	-1, // 1316
	34, // 1317
	34, // 1318
	-1, // 1319
	-1, // 1320
	34, // 1321
	34, // 1322
	36, // 1323
	36, // 1324
	33, // 1325
	-1, // 1326
	33, // 1327
	33, // 1328
	-1, // 1329
	-1, // 1330
	33, // 1331
	33, // 1332
	32, // 1333
	-1, // 1334
	32, // 1335
	32, // 1336
	-1, // 1337
	35, // 1338
	32, // 1339
	32, // 1340
	31, // 1341
	-1, // 1342
	31, // 1343
	31, // 1344
	-1, // 1345
	34, // 1346
	31, // 1347
	31, // 1348
	-1, // 1349
	-1, // 1350
	30, // 1351
	-1, // 1352
	30, // 1353
	30, // 1354
	-1, // 1355
	33, // 1356
	30, // 1357
	30, // 1358
	-1, // 1359
	35, // 1360
	35, // 1361
	-1, // 1362
	-1, // 1363
	32, // 1364
	-1, // 1365
	-1, // 1366
	-1, // 1367
	34, // 1368
	34, // 1369
	-1, // 1370
	-1, // 1371
	31, // 1372
	-1, // 1373
	-1, // 1374
	-1, // 1375
	-1, // 1376
	-1, // 1377
	33, // 1378
	33, // 1379
	-1, // 1380
	-1, // 1381
	30, // 1382
	-1, // 1383
	-1, // 1384
	-1, // 1385
	32, // 1386
	32, // 1387
	-1, // 1388
	-1, // 1389
	-1, // 1390
	-1, // 1391
	-1, // 1392
	-1, // 1393
	31, // 1394
	31, // 1395
	-1, // 1396
	-1, // 1397
	-1, // 1398
	-1, // 1399
	-1, // 1400
	-1, // 1401
	-1, // 1402
	-1, // 1403
	30, // 1404
	30, // 1405
}

var Base = []int{
	1092, // state 0
	1037, // state 1
	28,   // state 2
	608,  // state 3
	128,  // state 4
	160,  // state 5
	17,   // state 6
	1109, // state 7
	256,  // state 8
	0,    // state 9
	1164, // state 10
	320,  // state 11
	868,  // state 12
	1071, // state 13
	2,    // state 14
	2,    // state 15
	1173, // state 16
	999,  // state 17
	640,  // state 18
	3,    // state 19
	732,  // state 20
	978,  // state 21
	766,  // state 22
	1203, // state 23
	3,    // state 24
	672,  // state 25
	906,  // state 26
	32,   // state 27
	448,  // state 28
	944,  // state 29
	1341, // state 30
	1331, // state 31
	1323, // state 32
	1315, // state 33
	1305, // state 34
	1297, // state 35
	1260, // state 36
	1248, // state 37
	1240, // state 38
	1222, // state 39
	923,  // state 40
	1230, // state 41
	19,   // state 42
	35,   // state 43
	0,    // state 44
	1,    // state 45
	5,    // state 46
	6,    // state 47
	10,   // state 48
	192,  // state 49
	18,   // state 50
	224,  // state 51
	352,  // state 52
	384,  // state 53
	416,  // state 54
	96,   // state 55
	512,  // state 56
	544,  // state 57
	576,  // state 58
	64,   // state 59
	798,  // state 60
	734,  // state 61
	8,    // state 62
	35,   // state 63
	30,   // state 64
	742,  // state 65
	961,  // state 66
	1185, // state 67
	480,  // state 68
	885,  // state 69
	1054, // state 70
	288,  // state 71
	11,   // state 72
	1130, // state 73
	2,    // state 74
	32,   // state 75
	16,   // state 76
	20,   // state 77
	1147, // state 78
	5,    // state 79
	1016, // state 80
	37,   // state 81
}

var Gotos = []int{
	-1, // 0
	19, // 1
	-1, // 2
	65, // 3
	14, // 4
	13, // 5
	78, // 6
	72, // 7
	6,  // 8
	18, // 9
	2,  // 10
	3,  // 11
	25, // 12
	5,  // 13
	81, // 14
	-1, // 15
	7,  // 16
	17, // 17
	26, // 18
	21, // 19
	12, // 20
	44, // 21
	13, // 22
	-1, // 23
	-1, // 24
	6,  // 25
	18, // 26
	2,  // 27
	3,  // 28
	25, // 29
	5,  // 30
	-1, // 31
	-1, // 32
	7,  // 33
	17, // 34
	26, // 35
	21, // 36
	12, // 37
	75, // 38
	13, // 39
	-1, // 40
	-1, // 41
	6,  // 42
	18, // 43
	2,  // 44
	3,  // 45
	25, // 46
	5,  // 47
	-1, // 48
	-1, // 49
	7,  // 50
	17, // 51
	26, // 52
	21, // 53
	12, // 54
	63, // 55
	-1, // 56
	64, // 57
	18, // 58
	2,  // 59
	3,  // 60
	25, // 61
	5,  // 62
	77, // 63
	18, // 64
	2,  // 65
	3,  // 66
	25, // 67
	5,  // 68
	43, // 69
	18, // 70
	2,  // 71
	3,  // 72
	25, // 73
	5,  // 74
	47, // 75
	18, // 76
	2,  // 77
	3,  // 78
	25, // 79
	5,  // 80
	48, // 81
	18, // 82
	2,  // 83
	3,  // 84
	25, // 85
	5,  // 86
	76, // 87
	18, // 88
	2,  // 89
	3,  // 90
	25, // 91
	5,  // 92
	62, // 93
	18, // 94
	2,  // 95
	3,  // 96
	25, // 97
	5,  // 98
	18, // 99
	-1, // 100
	56, // 101
	25, // 102
	5,  // 103
	18, // 104
	-1, // 105
	52, // 106
	25, // 107
	5,  // 108
	18, // 109
	-1, // 110
	54, // 111
	25, // 112
	5,  // 113
	18, // 114
	-1, // 115
	57, // 116
	25, // 117
	5,  // 118
	18, // 119
	-1, // 120
	58, // 121
	25, // 122
	5,  // 123
	18, // 124
	-1, // 125
	59, // 126
	25, // 127
	5,  // 128
	18, // 129
	-1, // 130
	60, // 131
	25, // 132
	5,  // 133
	18, // 134
	-1, // 135
	61, // 136
	25, // 137
	5,  // 138
	18, // 139
	-1, // 140
	53, // 141
	25, // 142
	5,  // 143
	18, // 144
	-1, // 145
	55, // 146
	25, // 147
	5,  // 148
	18, // 149
	-1, // 150
	51, // 151
	25, // 152
	5,  // 153
	18, // 154
	-1, // 155
	18, // 156
	49, // 157
	5,  // 158
	28, // 159
	5,  // 160
}

var GotoCheck = []int{
	-1, // 0
	0,  // 1
	-1, // 2
	43, // 3
	0,  // 4
	0,  // 5
	74, // 6
	64, // 7
	0,  // 8
	0,  // 9
	0,  // 10
	0,  // 11
	0,  // 12
	0,  // 13
	77, // 14
	-1, // 15
	0,  // 16
	0,  // 17
	0,  // 18
	0,  // 19
	0,  // 20
	13, // 21
	13, // 22
	-1, // 23
	-1, // 24
	13, // 25
	13, // 26
	13, // 27
	13, // 28
	13, // 29
	13, // 30
	-1, // 31
	-1, // 32
	13, // 33
	13, // 34
	13, // 35
	13, // 36
	13, // 37
	66, // 38
	66, // 39
	-1, // 40
	-1, // 41
	66, // 42
	66, // 43
	66, // 44
	66, // 45
	66, // 46
	66, // 47
	-1, // 48
	-1, // 49
	66, // 50
	66, // 51
	66, // 52
	66, // 53
	66, // 54
	42, // 55
	-1, // 56
	42, // 57
	42, // 58
	42, // 59
	42, // 60
	42, // 61
	42, // 62
	73, // 63
	73, // 64
	73, // 65
	73, // 66
	73, // 67
	73, // 68
	10, // 69
	10, // 70
	10, // 71
	10, // 72
	10, // 73
	10, // 74
	16, // 75
	16, // 76
	16, // 77
	16, // 78
	16, // 79
	16, // 80
	20, // 81
	20, // 82
	20, // 83
	20, // 84
	20, // 85
	20, // 86
	67, // 87
	67, // 88
	67, // 89
	67, // 90
	67, // 91
	67, // 92
	41, // 93
	41, // 94
	41, // 95
	41, // 96
	41, // 97
	41, // 98
	34, // 99
	-1, // 100
	34, // 101
	34, // 102
	34, // 103
	30, // 104
	-1, // 105
	30, // 106
	30, // 107
	30, // 108
	32, // 109
	-1, // 110
	32, // 111
	32, // 112
	32, // 113
	35, // 114
	-1, // 115
	35, // 116
	35, // 117
	35, // 118
	36, // 119
	-1, // 120
	36, // 121
	36, // 122
	36, // 123
	37, // 124
	-1, // 125
	37, // 126
	37, // 127
	37, // 128
	38, // 129
	-1, // 130
	38, // 131
	38, // 132
	38, // 133
	39, // 134
	-1, // 135
	39, // 136
	39, // 137
	39, // 138
	31, // 139
	-1, // 140
	31, // 141
	31, // 142
	31, // 143
	33, // 144
	-1, // 145
	33, // 146
	33, // 147
	33, // 148
	29, // 149
	-1, // 150
	29, // 151
	29, // 152
	29, // 153
	23, // 154
	-1, // 155
	1,  // 156
	23, // 157
	23, // 158
	1,  // 159
	1,  // 160
}

var GotoBase = []int{
	0,   // state 0
	147, // state 1
	-1,  // state 2
	-1,  // state 3
	-1,  // state 4
	-1,  // state 5
	-1,  // state 6
	-1,  // state 7
	-1,  // state 8
	-1,  // state 9
	61,  // state 10
	-1,  // state 11
	-1,  // state 12
	17,  // state 13
	-1,  // state 14
	-1,  // state 15
	67,  // state 16
	-1,  // state 17
	-1,  // state 18
	-1,  // state 19
	73,  // state 20
	-1,  // state 21
	-1,  // state 22
	145, // state 23
	-1,  // state 24
	-1,  // state 25
	-1,  // state 26
	-1,  // state 27
	-1,  // state 28
	140, // state 29
	95,  // state 30
	130, // state 31
	100, // state 32
	135, // state 33
	90,  // state 34
	105, // state 35
	110, // state 36
	115, // state 37
	120, // state 38
	125, // state 39
	-1,  // state 40
	85,  // state 41
	49,  // state 42
	0,   // state 43
	-1,  // state 44
	-1,  // state 45
	-1,  // state 46
	-1,  // state 47
	-1,  // state 48
	-1,  // state 49
	-1,  // state 50
	-1,  // state 51
	-1,  // state 52
	-1,  // state 53
	-1,  // state 54
	-1,  // state 55
	-1,  // state 56
	-1,  // state 57
	-1,  // state 58
	-1,  // state 59
	-1,  // state 60
	-1,  // state 61
	-1,  // state 62
	-1,  // state 63
	0,   // state 64
	-1,  // state 65
	34,  // state 66
	79,  // state 67
	-1,  // state 68
	-1,  // state 69
	-1,  // state 70
	-1,  // state 71
	-1,  // state 72
	55,  // state 73
	3,   // state 74
	-1,  // state 75
	-1,  // state 76
	7,   // state 77
	-1,  // state 78
	-1,  // state 79
	-1,  // state 80
	-1,  // state 81
}

func Action(state int, tk Kind) ActionStruct {
	if state < 0 || state >= len(Base) {
		return Err(errors.Errors[6])
	}
	if tk <= 0 || int(tk) >= ActionTokenCount {
		return Err(errors.Errors[6])
	}
	b := Base[state]
	if b < 0 {
		return Err(errors.Errors[6])
	}
	idx := b + int(tk)
	if idx >= 0 && idx < len(Actions) && Check[idx] == state {
		return Actions[idx]
	}
	return Err(errors.Errors[6])
}

func Goto(state int, k ast.NodeType) int {
	if state < 0 || state >= len(GotoBase) {
		return -1
	}
	b := GotoBase[state]
	if b < 0 {
		return -1
	}
	idx := b + int(k)
	if idx >= 0 && idx < len(Gotos) && GotoCheck[idx] == state {
		return Gotos[idx]
	}
	return -1
}
